name: pythonoccapp  # overridden at install, so this is for your use with conda env
dependencies:
    - python=3.5
    - flask
    - conda-forge
    - dlr-sc
    - pythonocc
    - oce
    - pythonocc-core