# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _Geom2dHatch.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_Geom2dHatch')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_Geom2dHatch')
    _Geom2dHatch = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_Geom2dHatch', [dirname(__file__)])
        except ImportError:
            import _Geom2dHatch
            return _Geom2dHatch
        try:
            _mod = imp.load_module('_Geom2dHatch', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _Geom2dHatch = swig_import_helper()
    del swig_import_helper
else:
    import _Geom2dHatch
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


class SwigPyIterator(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _Geom2dHatch.delete_SwigPyIterator
    def __iter__(self):
        return self
SwigPyIterator.value = new_instancemethod(_Geom2dHatch.SwigPyIterator_value, None, SwigPyIterator)
SwigPyIterator.incr = new_instancemethod(_Geom2dHatch.SwigPyIterator_incr, None, SwigPyIterator)
SwigPyIterator.decr = new_instancemethod(_Geom2dHatch.SwigPyIterator_decr, None, SwigPyIterator)
SwigPyIterator.distance = new_instancemethod(_Geom2dHatch.SwigPyIterator_distance, None, SwigPyIterator)
SwigPyIterator.equal = new_instancemethod(_Geom2dHatch.SwigPyIterator_equal, None, SwigPyIterator)
SwigPyIterator.copy = new_instancemethod(_Geom2dHatch.SwigPyIterator_copy, None, SwigPyIterator)
SwigPyIterator.next = new_instancemethod(_Geom2dHatch.SwigPyIterator_next, None, SwigPyIterator)
SwigPyIterator.__next__ = new_instancemethod(_Geom2dHatch.SwigPyIterator___next__, None, SwigPyIterator)
SwigPyIterator.previous = new_instancemethod(_Geom2dHatch.SwigPyIterator_previous, None, SwigPyIterator)
SwigPyIterator.advance = new_instancemethod(_Geom2dHatch.SwigPyIterator_advance, None, SwigPyIterator)
SwigPyIterator.__eq__ = new_instancemethod(_Geom2dHatch.SwigPyIterator___eq__, None, SwigPyIterator)
SwigPyIterator.__ne__ = new_instancemethod(_Geom2dHatch.SwigPyIterator___ne__, None, SwigPyIterator)
SwigPyIterator.__iadd__ = new_instancemethod(_Geom2dHatch.SwigPyIterator___iadd__, None, SwigPyIterator)
SwigPyIterator.__isub__ = new_instancemethod(_Geom2dHatch.SwigPyIterator___isub__, None, SwigPyIterator)
SwigPyIterator.__add__ = new_instancemethod(_Geom2dHatch.SwigPyIterator___add__, None, SwigPyIterator)
SwigPyIterator.__sub__ = new_instancemethod(_Geom2dHatch.SwigPyIterator___sub__, None, SwigPyIterator)
SwigPyIterator_swigregister = _Geom2dHatch.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)


def _dumps_object(klass):
    """ Improve string output for any oce object.
    By default, __repr__ method returns something like:
    <OCC.TopoDS.TopoDS_Shape; proxy of <Swig Object of type 'TopoDS_Shape *' at 0x02BB0758> >
    This is too much verbose.
    We prefer :
    class<'gp_Pnt'>
    or
    class<'TopoDS_Shape'; Type:Solid; Id:59391729>
    """
    klass_name = str(klass.__class__).split(".")[2].split("'")[0]
    repr_string = "class<'" + klass_name + "'"
# for TopoDS_Shape, we also look for the base type
    if klass_name == "TopoDS_Shape":
        st = klass.ShapeType()
        types = {OCC.TopAbs.TopAbs_VERTEX:"Vertex",
                 OCC.TopAbs.TopAbs_SOLID:"Solid",
                 OCC.TopAbs.TopAbs_EDGE:"Edge",
                 OCC.TopAbs.TopAbs_FACE:"Face",
                 OCC.TopAbs.TopAbs_SHELL:"Shell",
                 OCC.TopAbs.TopAbs_WIRE:"Wire",
                 OCC.TopAbs.TopAbs_COMPOUND:"Compound",
                 OCC.TopAbs.TopAbs_COMPSOLID:"Compsolid."}
        repr_string += "; Type:%s" % types[st]        
# for each class that has an HashCode method define,
# print the id
    if hasattr(klass, "HashCode"):
        klass_id = hash(klass)
        repr_string += "; id:%s" % klass_id
    repr_string += ">"
    return repr_string

import OCC.gp
import OCC.Standard
import OCC.TopAbs
import OCC.Geom2dAdaptor
import OCC.Adaptor2d
import OCC.GeomAbs
import OCC.TColStd
import OCC.TCollection
import OCC.MMgt
import OCC.Geom2d
import OCC.TColgp
import OCC.IntRes2d
import OCC.HatchGen
import OCC.Geom2dInt
import OCC.math
import OCC.IntCurve
import OCC.Extrema
import OCC.Adaptor3d
import OCC.Geom
import OCC.Intf
import OCC.Bnd

def register_handle(handle, base_object):
    """
    Inserts the handle into the base object to
    prevent memory corruption in certain cases
    """
    try:
        if base_object.IsKind("Standard_Transient"):
            base_object.thisHandle = handle
            base_object.thisown = False
    except:
        pass

class Geom2dHatch_Classifier(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        :param F:
        :type F: Geom2dHatch_Elements &
        :param P:
        :type P: gp_Pnt2d
        :param Tol:
        :type Tol: float
        :rtype: None

        """
        _Geom2dHatch.Geom2dHatch_Classifier_swiginit(self, _Geom2dHatch.new_Geom2dHatch_Classifier(*args))

    def Perform(self, *args) -> "void":
        """
        :param F:
        :type F: Geom2dHatch_Elements &
        :param P:
        :type P: gp_Pnt2d
        :param Tol:
        :type Tol: float
        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_Classifier_Perform(self, *args)


    def State(self, *args) -> "TopAbs_State":
        """
        :rtype: TopAbs_State

        """
        return _Geom2dHatch.Geom2dHatch_Classifier_State(self, *args)


    def Rejected(self, *args) -> "Standard_Boolean":
        """
        :rtype: bool

        """
        return _Geom2dHatch.Geom2dHatch_Classifier_Rejected(self, *args)


    def NoWires(self, *args) -> "Standard_Boolean":
        """
        :rtype: bool

        """
        return _Geom2dHatch.Geom2dHatch_Classifier_NoWires(self, *args)


    def Edge(self, *args) -> "Geom2dAdaptor_Curve const &":
        """
        :rtype: Geom2dAdaptor_Curve

        """
        return _Geom2dHatch.Geom2dHatch_Classifier_Edge(self, *args)


    def EdgeParameter(self, *args) -> "Standard_Real":
        """
        :rtype: float

        """
        return _Geom2dHatch.Geom2dHatch_Classifier_EdgeParameter(self, *args)


    def Position(self, *args) -> "IntRes2d_Position":
        """
        :rtype: IntRes2d_Position

        """
        return _Geom2dHatch.Geom2dHatch_Classifier_Position(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _Geom2dHatch.delete_Geom2dHatch_Classifier
Geom2dHatch_Classifier.Perform = new_instancemethod(_Geom2dHatch.Geom2dHatch_Classifier_Perform, None, Geom2dHatch_Classifier)
Geom2dHatch_Classifier.State = new_instancemethod(_Geom2dHatch.Geom2dHatch_Classifier_State, None, Geom2dHatch_Classifier)
Geom2dHatch_Classifier.Rejected = new_instancemethod(_Geom2dHatch.Geom2dHatch_Classifier_Rejected, None, Geom2dHatch_Classifier)
Geom2dHatch_Classifier.NoWires = new_instancemethod(_Geom2dHatch.Geom2dHatch_Classifier_NoWires, None, Geom2dHatch_Classifier)
Geom2dHatch_Classifier.Edge = new_instancemethod(_Geom2dHatch.Geom2dHatch_Classifier_Edge, None, Geom2dHatch_Classifier)
Geom2dHatch_Classifier.EdgeParameter = new_instancemethod(_Geom2dHatch.Geom2dHatch_Classifier_EdgeParameter, None, Geom2dHatch_Classifier)
Geom2dHatch_Classifier.Position = new_instancemethod(_Geom2dHatch.Geom2dHatch_Classifier_Position, None, Geom2dHatch_Classifier)
Geom2dHatch_Classifier_swigregister = _Geom2dHatch.Geom2dHatch_Classifier_swigregister
Geom2dHatch_Classifier_swigregister(Geom2dHatch_Classifier)

class Geom2dHatch_DataMapIteratorOfHatchings(OCC.TCollection.TCollection_BasicMapIterator):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        :param aMap:
        :type aMap: Geom2dHatch_Hatchings &
        :rtype: None

        """
        _Geom2dHatch.Geom2dHatch_DataMapIteratorOfHatchings_swiginit(self, _Geom2dHatch.new_Geom2dHatch_DataMapIteratorOfHatchings(*args))

    def Initialize(self, *args) -> "void":
        """
        :param aMap:
        :type aMap: Geom2dHatch_Hatchings &
        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_DataMapIteratorOfHatchings_Initialize(self, *args)


    def Key(self, *args) -> "Standard_Integer const &":
        """
        :rtype: int

        """
        return _Geom2dHatch.Geom2dHatch_DataMapIteratorOfHatchings_Key(self, *args)


    def Value(self, *args) -> "Geom2dHatch_Hatching const &":
        """
        :rtype: Geom2dHatch_Hatching

        """
        return _Geom2dHatch.Geom2dHatch_DataMapIteratorOfHatchings_Value(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _Geom2dHatch.delete_Geom2dHatch_DataMapIteratorOfHatchings
Geom2dHatch_DataMapIteratorOfHatchings.Initialize = new_instancemethod(_Geom2dHatch.Geom2dHatch_DataMapIteratorOfHatchings_Initialize, None, Geom2dHatch_DataMapIteratorOfHatchings)
Geom2dHatch_DataMapIteratorOfHatchings.Key = new_instancemethod(_Geom2dHatch.Geom2dHatch_DataMapIteratorOfHatchings_Key, None, Geom2dHatch_DataMapIteratorOfHatchings)
Geom2dHatch_DataMapIteratorOfHatchings.Value = new_instancemethod(_Geom2dHatch.Geom2dHatch_DataMapIteratorOfHatchings_Value, None, Geom2dHatch_DataMapIteratorOfHatchings)
Geom2dHatch_DataMapIteratorOfHatchings_swigregister = _Geom2dHatch.Geom2dHatch_DataMapIteratorOfHatchings_swigregister
Geom2dHatch_DataMapIteratorOfHatchings_swigregister(Geom2dHatch_DataMapIteratorOfHatchings)

class Geom2dHatch_DataMapIteratorOfMapOfElements(OCC.TCollection.TCollection_BasicMapIterator):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        :param aMap:
        :type aMap: Geom2dHatch_MapOfElements &
        :rtype: None

        """
        _Geom2dHatch.Geom2dHatch_DataMapIteratorOfMapOfElements_swiginit(self, _Geom2dHatch.new_Geom2dHatch_DataMapIteratorOfMapOfElements(*args))

    def Initialize(self, *args) -> "void":
        """
        :param aMap:
        :type aMap: Geom2dHatch_MapOfElements &
        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_DataMapIteratorOfMapOfElements_Initialize(self, *args)


    def Key(self, *args) -> "Standard_Integer const &":
        """
        :rtype: int

        """
        return _Geom2dHatch.Geom2dHatch_DataMapIteratorOfMapOfElements_Key(self, *args)


    def Value(self, *args) -> "Geom2dHatch_Element const &":
        """
        :rtype: Geom2dHatch_Element

        """
        return _Geom2dHatch.Geom2dHatch_DataMapIteratorOfMapOfElements_Value(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _Geom2dHatch.delete_Geom2dHatch_DataMapIteratorOfMapOfElements
Geom2dHatch_DataMapIteratorOfMapOfElements.Initialize = new_instancemethod(_Geom2dHatch.Geom2dHatch_DataMapIteratorOfMapOfElements_Initialize, None, Geom2dHatch_DataMapIteratorOfMapOfElements)
Geom2dHatch_DataMapIteratorOfMapOfElements.Key = new_instancemethod(_Geom2dHatch.Geom2dHatch_DataMapIteratorOfMapOfElements_Key, None, Geom2dHatch_DataMapIteratorOfMapOfElements)
Geom2dHatch_DataMapIteratorOfMapOfElements.Value = new_instancemethod(_Geom2dHatch.Geom2dHatch_DataMapIteratorOfMapOfElements_Value, None, Geom2dHatch_DataMapIteratorOfMapOfElements)
Geom2dHatch_DataMapIteratorOfMapOfElements_swigregister = _Geom2dHatch.Geom2dHatch_DataMapIteratorOfMapOfElements_swigregister
Geom2dHatch_DataMapIteratorOfMapOfElements_swigregister(Geom2dHatch_DataMapIteratorOfMapOfElements)

class Geom2dHatch_DataMapNodeOfHatchings(OCC.TCollection.TCollection_MapNode):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :param K:
        :type K: int &
        :param I:
        :type I: Geom2dHatch_Hatching &
        :param n:
        :type n: TCollection_MapNodePtr &
        :rtype: None

        """
        _Geom2dHatch.Geom2dHatch_DataMapNodeOfHatchings_swiginit(self, _Geom2dHatch.new_Geom2dHatch_DataMapNodeOfHatchings(*args))

    def GetKey(self) -> "Standard_Integer":
        """GetKey(Geom2dHatch_DataMapNodeOfHatchings self) -> Standard_Integer"""
        return _Geom2dHatch.Geom2dHatch_DataMapNodeOfHatchings_GetKey(self)


    def SetKey(self, value: 'Standard_Integer') -> "void":
        """SetKey(Geom2dHatch_DataMapNodeOfHatchings self, Standard_Integer value)"""
        return _Geom2dHatch.Geom2dHatch_DataMapNodeOfHatchings_SetKey(self, value)


    def Value(self, *args) -> "Geom2dHatch_Hatching &":
        """
        :rtype: Geom2dHatch_Hatching

        """
        return _Geom2dHatch.Geom2dHatch_DataMapNodeOfHatchings_Value(self, *args)


    def GetHandle(self):
        try:
            return self.thisHandle
        except:
            self.thisHandle = Handle_Geom2dHatch_DataMapNodeOfHatchings(self)
            self.thisown = False
            return self.thisHandle


    __repr__ = _dumps_object

    __swig_destroy__ = _Geom2dHatch.delete_Geom2dHatch_DataMapNodeOfHatchings
Geom2dHatch_DataMapNodeOfHatchings.GetKey = new_instancemethod(_Geom2dHatch.Geom2dHatch_DataMapNodeOfHatchings_GetKey, None, Geom2dHatch_DataMapNodeOfHatchings)
Geom2dHatch_DataMapNodeOfHatchings.SetKey = new_instancemethod(_Geom2dHatch.Geom2dHatch_DataMapNodeOfHatchings_SetKey, None, Geom2dHatch_DataMapNodeOfHatchings)
Geom2dHatch_DataMapNodeOfHatchings.Value = new_instancemethod(_Geom2dHatch.Geom2dHatch_DataMapNodeOfHatchings_Value, None, Geom2dHatch_DataMapNodeOfHatchings)
Geom2dHatch_DataMapNodeOfHatchings_swigregister = _Geom2dHatch.Geom2dHatch_DataMapNodeOfHatchings_swigregister
Geom2dHatch_DataMapNodeOfHatchings_swigregister(Geom2dHatch_DataMapNodeOfHatchings)

class Handle_Geom2dHatch_DataMapNodeOfHatchings(OCC.TCollection.Handle_TCollection_MapNode):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        _Geom2dHatch.Handle_Geom2dHatch_DataMapNodeOfHatchings_swiginit(self, _Geom2dHatch.new_Handle_Geom2dHatch_DataMapNodeOfHatchings(*args))

            # register the handle in the base object
        if len(args) > 0:
            register_handle(self, args[0])



    DownCast = staticmethod(_Geom2dHatch.Handle_Geom2dHatch_DataMapNodeOfHatchings_DownCast)

    def GetObject(self):
        obj = self._get_reference()
        register_handle(self, obj)
        return obj

    __swig_destroy__ = _Geom2dHatch.delete_Handle_Geom2dHatch_DataMapNodeOfHatchings
Handle_Geom2dHatch_DataMapNodeOfHatchings.Nullify = new_instancemethod(_Geom2dHatch.Handle_Geom2dHatch_DataMapNodeOfHatchings_Nullify, None, Handle_Geom2dHatch_DataMapNodeOfHatchings)
Handle_Geom2dHatch_DataMapNodeOfHatchings.IsNull = new_instancemethod(_Geom2dHatch.Handle_Geom2dHatch_DataMapNodeOfHatchings_IsNull, None, Handle_Geom2dHatch_DataMapNodeOfHatchings)
Handle_Geom2dHatch_DataMapNodeOfHatchings._get_reference = new_instancemethod(_Geom2dHatch.Handle_Geom2dHatch_DataMapNodeOfHatchings__get_reference, None, Handle_Geom2dHatch_DataMapNodeOfHatchings)
Handle_Geom2dHatch_DataMapNodeOfHatchings_swigregister = _Geom2dHatch.Handle_Geom2dHatch_DataMapNodeOfHatchings_swigregister
Handle_Geom2dHatch_DataMapNodeOfHatchings_swigregister(Handle_Geom2dHatch_DataMapNodeOfHatchings)

def Handle_Geom2dHatch_DataMapNodeOfHatchings_DownCast(AnObject: 'Handle_Standard_Transient') -> "Handle_Geom2dHatch_DataMapNodeOfHatchings const":
    return _Geom2dHatch.Handle_Geom2dHatch_DataMapNodeOfHatchings_DownCast(AnObject)
Handle_Geom2dHatch_DataMapNodeOfHatchings_DownCast = _Geom2dHatch.Handle_Geom2dHatch_DataMapNodeOfHatchings_DownCast

class Geom2dHatch_DataMapNodeOfMapOfElements(OCC.TCollection.TCollection_MapNode):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :param K:
        :type K: int &
        :param I:
        :type I: Geom2dHatch_Element &
        :param n:
        :type n: TCollection_MapNodePtr &
        :rtype: None

        """
        _Geom2dHatch.Geom2dHatch_DataMapNodeOfMapOfElements_swiginit(self, _Geom2dHatch.new_Geom2dHatch_DataMapNodeOfMapOfElements(*args))

    def GetKey(self) -> "Standard_Integer":
        """GetKey(Geom2dHatch_DataMapNodeOfMapOfElements self) -> Standard_Integer"""
        return _Geom2dHatch.Geom2dHatch_DataMapNodeOfMapOfElements_GetKey(self)


    def SetKey(self, value: 'Standard_Integer') -> "void":
        """SetKey(Geom2dHatch_DataMapNodeOfMapOfElements self, Standard_Integer value)"""
        return _Geom2dHatch.Geom2dHatch_DataMapNodeOfMapOfElements_SetKey(self, value)


    def Value(self, *args) -> "Geom2dHatch_Element &":
        """
        :rtype: Geom2dHatch_Element

        """
        return _Geom2dHatch.Geom2dHatch_DataMapNodeOfMapOfElements_Value(self, *args)


    def GetHandle(self):
        try:
            return self.thisHandle
        except:
            self.thisHandle = Handle_Geom2dHatch_DataMapNodeOfMapOfElements(self)
            self.thisown = False
            return self.thisHandle


    __repr__ = _dumps_object

    __swig_destroy__ = _Geom2dHatch.delete_Geom2dHatch_DataMapNodeOfMapOfElements
Geom2dHatch_DataMapNodeOfMapOfElements.GetKey = new_instancemethod(_Geom2dHatch.Geom2dHatch_DataMapNodeOfMapOfElements_GetKey, None, Geom2dHatch_DataMapNodeOfMapOfElements)
Geom2dHatch_DataMapNodeOfMapOfElements.SetKey = new_instancemethod(_Geom2dHatch.Geom2dHatch_DataMapNodeOfMapOfElements_SetKey, None, Geom2dHatch_DataMapNodeOfMapOfElements)
Geom2dHatch_DataMapNodeOfMapOfElements.Value = new_instancemethod(_Geom2dHatch.Geom2dHatch_DataMapNodeOfMapOfElements_Value, None, Geom2dHatch_DataMapNodeOfMapOfElements)
Geom2dHatch_DataMapNodeOfMapOfElements_swigregister = _Geom2dHatch.Geom2dHatch_DataMapNodeOfMapOfElements_swigregister
Geom2dHatch_DataMapNodeOfMapOfElements_swigregister(Geom2dHatch_DataMapNodeOfMapOfElements)

class Handle_Geom2dHatch_DataMapNodeOfMapOfElements(OCC.TCollection.Handle_TCollection_MapNode):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        _Geom2dHatch.Handle_Geom2dHatch_DataMapNodeOfMapOfElements_swiginit(self, _Geom2dHatch.new_Handle_Geom2dHatch_DataMapNodeOfMapOfElements(*args))

            # register the handle in the base object
        if len(args) > 0:
            register_handle(self, args[0])



    DownCast = staticmethod(_Geom2dHatch.Handle_Geom2dHatch_DataMapNodeOfMapOfElements_DownCast)

    def GetObject(self):
        obj = self._get_reference()
        register_handle(self, obj)
        return obj

    __swig_destroy__ = _Geom2dHatch.delete_Handle_Geom2dHatch_DataMapNodeOfMapOfElements
Handle_Geom2dHatch_DataMapNodeOfMapOfElements.Nullify = new_instancemethod(_Geom2dHatch.Handle_Geom2dHatch_DataMapNodeOfMapOfElements_Nullify, None, Handle_Geom2dHatch_DataMapNodeOfMapOfElements)
Handle_Geom2dHatch_DataMapNodeOfMapOfElements.IsNull = new_instancemethod(_Geom2dHatch.Handle_Geom2dHatch_DataMapNodeOfMapOfElements_IsNull, None, Handle_Geom2dHatch_DataMapNodeOfMapOfElements)
Handle_Geom2dHatch_DataMapNodeOfMapOfElements._get_reference = new_instancemethod(_Geom2dHatch.Handle_Geom2dHatch_DataMapNodeOfMapOfElements__get_reference, None, Handle_Geom2dHatch_DataMapNodeOfMapOfElements)
Handle_Geom2dHatch_DataMapNodeOfMapOfElements_swigregister = _Geom2dHatch.Handle_Geom2dHatch_DataMapNodeOfMapOfElements_swigregister
Handle_Geom2dHatch_DataMapNodeOfMapOfElements_swigregister(Handle_Geom2dHatch_DataMapNodeOfMapOfElements)

def Handle_Geom2dHatch_DataMapNodeOfMapOfElements_DownCast(AnObject: 'Handle_Standard_Transient') -> "Handle_Geom2dHatch_DataMapNodeOfMapOfElements const":
    return _Geom2dHatch.Handle_Geom2dHatch_DataMapNodeOfMapOfElements_DownCast(AnObject)
Handle_Geom2dHatch_DataMapNodeOfMapOfElements_DownCast = _Geom2dHatch.Handle_Geom2dHatch_DataMapNodeOfMapOfElements_DownCast

class Geom2dHatch_Element(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        * Magic constructor.

        :param Other:
        :type Other: Geom2dHatch_Element &
        :rtype: None

        * Creates an element.

        :param Curve:
        :type Curve: Geom2dAdaptor_Curve &
        :param Orientation: default value is TopAbs_FORWARD
        :type Orientation: TopAbs_Orientation
        :rtype: None

        """
        _Geom2dHatch.Geom2dHatch_Element_swiginit(self, _Geom2dHatch.new_Geom2dHatch_Element(*args))

    def Curve(self, *args) -> "Geom2dAdaptor_Curve const &":
        """
        * Returns the curve associated to the element.

        :rtype: Geom2dAdaptor_Curve

        """
        return _Geom2dHatch.Geom2dHatch_Element_Curve(self, *args)


    def ChangeCurve(self, *args) -> "Geom2dAdaptor_Curve &":
        """
        * Returns the curve associated to the element.

        :rtype: Geom2dAdaptor_Curve

        """
        return _Geom2dHatch.Geom2dHatch_Element_ChangeCurve(self, *args)


    def Orientation(self, *args) -> "TopAbs_Orientation":
        """
        * Sets the orientation of the element.

        :param Orientation:
        :type Orientation: TopAbs_Orientation
        :rtype: None

        * Returns the orientation of the element.

        :rtype: TopAbs_Orientation

        """
        return _Geom2dHatch.Geom2dHatch_Element_Orientation(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _Geom2dHatch.delete_Geom2dHatch_Element
Geom2dHatch_Element.Curve = new_instancemethod(_Geom2dHatch.Geom2dHatch_Element_Curve, None, Geom2dHatch_Element)
Geom2dHatch_Element.ChangeCurve = new_instancemethod(_Geom2dHatch.Geom2dHatch_Element_ChangeCurve, None, Geom2dHatch_Element)
Geom2dHatch_Element.Orientation = new_instancemethod(_Geom2dHatch.Geom2dHatch_Element_Orientation, None, Geom2dHatch_Element)
Geom2dHatch_Element_swigregister = _Geom2dHatch.Geom2dHatch_Element_swigregister
Geom2dHatch_Element_swigregister(Geom2dHatch_Element)

class Geom2dHatch_Elements(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        :param Other:
        :type Other: Geom2dHatch_Elements &
        :rtype: None

        """
        _Geom2dHatch.Geom2dHatch_Elements_swiginit(self, _Geom2dHatch.new_Geom2dHatch_Elements(*args))

    def Clear(self, *args) -> "void":
        """
        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_Elements_Clear(self, *args)


    def Bind(self, *args) -> "Standard_Boolean":
        """
        :param K:
        :type K: int
        :param I:
        :type I: Geom2dHatch_Element &
        :rtype: bool

        """
        return _Geom2dHatch.Geom2dHatch_Elements_Bind(self, *args)


    def IsBound(self, *args) -> "Standard_Boolean":
        """
        :param K:
        :type K: int
        :rtype: bool

        """
        return _Geom2dHatch.Geom2dHatch_Elements_IsBound(self, *args)


    def UnBind(self, *args) -> "Standard_Boolean":
        """
        :param K:
        :type K: int
        :rtype: bool

        """
        return _Geom2dHatch.Geom2dHatch_Elements_UnBind(self, *args)


    def Find(self, *args) -> "Geom2dHatch_Element const &":
        """
        :param K:
        :type K: int
        :rtype: Geom2dHatch_Element

        """
        return _Geom2dHatch.Geom2dHatch_Elements_Find(self, *args)


    def ChangeFind(self, *args) -> "Geom2dHatch_Element &":
        """
        :param K:
        :type K: int
        :rtype: Geom2dHatch_Element

        """
        return _Geom2dHatch.Geom2dHatch_Elements_ChangeFind(self, *args)


    def Reject(self, *args) -> "Standard_Boolean":
        """
        :param P:
        :type P: gp_Pnt2d
        :rtype: bool

        """
        return _Geom2dHatch.Geom2dHatch_Elements_Reject(self, *args)


    def Segment(self, *args) -> "Standard_Boolean":
        """
        :param P:
        :type P: gp_Pnt2d
        :param L:
        :type L: gp_Lin2d
        :param Par:
        :type Par: float &
        :rtype: bool

        """
        return _Geom2dHatch.Geom2dHatch_Elements_Segment(self, *args)


    def OtherSegment(self, *args) -> "Standard_Boolean":
        """
        :param P:
        :type P: gp_Pnt2d
        :param L:
        :type L: gp_Lin2d
        :param Par:
        :type Par: float &
        :rtype: bool

        """
        return _Geom2dHatch.Geom2dHatch_Elements_OtherSegment(self, *args)


    def InitWires(self, *args) -> "void":
        """
        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_Elements_InitWires(self, *args)


    def MoreWires(self, *args) -> "Standard_Boolean":
        """
        :rtype: bool

        """
        return _Geom2dHatch.Geom2dHatch_Elements_MoreWires(self, *args)


    def NextWire(self, *args) -> "void":
        """
        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_Elements_NextWire(self, *args)


    def RejectWire(self, *args) -> "Standard_Boolean":
        """
        :param L:
        :type L: gp_Lin2d
        :param Par:
        :type Par: float
        :rtype: bool

        """
        return _Geom2dHatch.Geom2dHatch_Elements_RejectWire(self, *args)


    def InitEdges(self, *args) -> "void":
        """
        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_Elements_InitEdges(self, *args)


    def MoreEdges(self, *args) -> "Standard_Boolean":
        """
        :rtype: bool

        """
        return _Geom2dHatch.Geom2dHatch_Elements_MoreEdges(self, *args)


    def NextEdge(self, *args) -> "void":
        """
        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_Elements_NextEdge(self, *args)


    def RejectEdge(self, *args) -> "Standard_Boolean":
        """
        :param L:
        :type L: gp_Lin2d
        :param Par:
        :type Par: float
        :rtype: bool

        """
        return _Geom2dHatch.Geom2dHatch_Elements_RejectEdge(self, *args)


    def CurrentEdge(self, *args) -> "void":
        """
        :param E:
        :type E: Geom2dAdaptor_Curve &
        :param Or:
        :type Or: TopAbs_Orientation &
        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_Elements_CurrentEdge(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _Geom2dHatch.delete_Geom2dHatch_Elements
Geom2dHatch_Elements.Clear = new_instancemethod(_Geom2dHatch.Geom2dHatch_Elements_Clear, None, Geom2dHatch_Elements)
Geom2dHatch_Elements.Bind = new_instancemethod(_Geom2dHatch.Geom2dHatch_Elements_Bind, None, Geom2dHatch_Elements)
Geom2dHatch_Elements.IsBound = new_instancemethod(_Geom2dHatch.Geom2dHatch_Elements_IsBound, None, Geom2dHatch_Elements)
Geom2dHatch_Elements.UnBind = new_instancemethod(_Geom2dHatch.Geom2dHatch_Elements_UnBind, None, Geom2dHatch_Elements)
Geom2dHatch_Elements.Find = new_instancemethod(_Geom2dHatch.Geom2dHatch_Elements_Find, None, Geom2dHatch_Elements)
Geom2dHatch_Elements.ChangeFind = new_instancemethod(_Geom2dHatch.Geom2dHatch_Elements_ChangeFind, None, Geom2dHatch_Elements)
Geom2dHatch_Elements.Reject = new_instancemethod(_Geom2dHatch.Geom2dHatch_Elements_Reject, None, Geom2dHatch_Elements)
Geom2dHatch_Elements.Segment = new_instancemethod(_Geom2dHatch.Geom2dHatch_Elements_Segment, None, Geom2dHatch_Elements)
Geom2dHatch_Elements.OtherSegment = new_instancemethod(_Geom2dHatch.Geom2dHatch_Elements_OtherSegment, None, Geom2dHatch_Elements)
Geom2dHatch_Elements.InitWires = new_instancemethod(_Geom2dHatch.Geom2dHatch_Elements_InitWires, None, Geom2dHatch_Elements)
Geom2dHatch_Elements.MoreWires = new_instancemethod(_Geom2dHatch.Geom2dHatch_Elements_MoreWires, None, Geom2dHatch_Elements)
Geom2dHatch_Elements.NextWire = new_instancemethod(_Geom2dHatch.Geom2dHatch_Elements_NextWire, None, Geom2dHatch_Elements)
Geom2dHatch_Elements.RejectWire = new_instancemethod(_Geom2dHatch.Geom2dHatch_Elements_RejectWire, None, Geom2dHatch_Elements)
Geom2dHatch_Elements.InitEdges = new_instancemethod(_Geom2dHatch.Geom2dHatch_Elements_InitEdges, None, Geom2dHatch_Elements)
Geom2dHatch_Elements.MoreEdges = new_instancemethod(_Geom2dHatch.Geom2dHatch_Elements_MoreEdges, None, Geom2dHatch_Elements)
Geom2dHatch_Elements.NextEdge = new_instancemethod(_Geom2dHatch.Geom2dHatch_Elements_NextEdge, None, Geom2dHatch_Elements)
Geom2dHatch_Elements.RejectEdge = new_instancemethod(_Geom2dHatch.Geom2dHatch_Elements_RejectEdge, None, Geom2dHatch_Elements)
Geom2dHatch_Elements.CurrentEdge = new_instancemethod(_Geom2dHatch.Geom2dHatch_Elements_CurrentEdge, None, Geom2dHatch_Elements)
Geom2dHatch_Elements_swigregister = _Geom2dHatch.Geom2dHatch_Elements_swigregister
Geom2dHatch_Elements_swigregister(Geom2dHatch_Elements)

class Geom2dHatch_FClass2dOfClassifier(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        """
        _Geom2dHatch.Geom2dHatch_FClass2dOfClassifier_swiginit(self, _Geom2dHatch.new_Geom2dHatch_FClass2dOfClassifier(*args))

    def Reset(self, *args) -> "void":
        """
        :param L:
        :type L: gp_Lin2d
        :param P:
        :type P: float
        :param Tol:
        :type Tol: float
        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_FClass2dOfClassifier_Reset(self, *args)


    def Compare(self, *args) -> "void":
        """
        :param E:
        :type E: Geom2dAdaptor_Curve &
        :param Or:
        :type Or: TopAbs_Orientation
        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_FClass2dOfClassifier_Compare(self, *args)


    def Parameter(self, *args) -> "Standard_Real":
        """
        :rtype: float

        """
        return _Geom2dHatch.Geom2dHatch_FClass2dOfClassifier_Parameter(self, *args)


    def Intersector(self, *args) -> "Geom2dHatch_Intersector &":
        """
        :rtype: Geom2dHatch_Intersector

        """
        return _Geom2dHatch.Geom2dHatch_FClass2dOfClassifier_Intersector(self, *args)


    def ClosestIntersection(self, *args) -> "Standard_Integer":
        """
        :rtype: int

        """
        return _Geom2dHatch.Geom2dHatch_FClass2dOfClassifier_ClosestIntersection(self, *args)


    def State(self, *args) -> "TopAbs_State":
        """
        :rtype: TopAbs_State

        """
        return _Geom2dHatch.Geom2dHatch_FClass2dOfClassifier_State(self, *args)


    def IsHeadOrEnd(self, *args) -> "Standard_Boolean":
        """
        :rtype: bool

        """
        return _Geom2dHatch.Geom2dHatch_FClass2dOfClassifier_IsHeadOrEnd(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _Geom2dHatch.delete_Geom2dHatch_FClass2dOfClassifier
Geom2dHatch_FClass2dOfClassifier.Reset = new_instancemethod(_Geom2dHatch.Geom2dHatch_FClass2dOfClassifier_Reset, None, Geom2dHatch_FClass2dOfClassifier)
Geom2dHatch_FClass2dOfClassifier.Compare = new_instancemethod(_Geom2dHatch.Geom2dHatch_FClass2dOfClassifier_Compare, None, Geom2dHatch_FClass2dOfClassifier)
Geom2dHatch_FClass2dOfClassifier.Parameter = new_instancemethod(_Geom2dHatch.Geom2dHatch_FClass2dOfClassifier_Parameter, None, Geom2dHatch_FClass2dOfClassifier)
Geom2dHatch_FClass2dOfClassifier.Intersector = new_instancemethod(_Geom2dHatch.Geom2dHatch_FClass2dOfClassifier_Intersector, None, Geom2dHatch_FClass2dOfClassifier)
Geom2dHatch_FClass2dOfClassifier.ClosestIntersection = new_instancemethod(_Geom2dHatch.Geom2dHatch_FClass2dOfClassifier_ClosestIntersection, None, Geom2dHatch_FClass2dOfClassifier)
Geom2dHatch_FClass2dOfClassifier.State = new_instancemethod(_Geom2dHatch.Geom2dHatch_FClass2dOfClassifier_State, None, Geom2dHatch_FClass2dOfClassifier)
Geom2dHatch_FClass2dOfClassifier.IsHeadOrEnd = new_instancemethod(_Geom2dHatch.Geom2dHatch_FClass2dOfClassifier_IsHeadOrEnd, None, Geom2dHatch_FClass2dOfClassifier)
Geom2dHatch_FClass2dOfClassifier_swigregister = _Geom2dHatch.Geom2dHatch_FClass2dOfClassifier_swigregister
Geom2dHatch_FClass2dOfClassifier_swigregister(Geom2dHatch_FClass2dOfClassifier)

class Geom2dHatch_Hatcher(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        * Returns an empty hatcher.

        :param Intersector:
        :type Intersector: Geom2dHatch_Intersector &
        :param Confusion2d:
        :type Confusion2d: float
        :param Confusion3d:
        :type Confusion3d: float
        :param KeepPnt: default value is Standard_False
        :type KeepPnt: bool
        :param KeepSeg: default value is Standard_False
        :type KeepSeg: bool
        :rtype: None

        """
        _Geom2dHatch.Geom2dHatch_Hatcher_swiginit(self, _Geom2dHatch.new_Geom2dHatch_Hatcher(*args))

    def Intersector(self, *args) -> "Geom2dHatch_Intersector const &":
        """
        * Sets the associated intersector.

        :param Intersector:
        :type Intersector: Geom2dHatch_Intersector &
        :rtype: None

        * Returns the associated intersector.

        :rtype: Geom2dHatch_Intersector

        """
        return _Geom2dHatch.Geom2dHatch_Hatcher_Intersector(self, *args)


    def ChangeIntersector(self, *args) -> "Geom2dHatch_Intersector &":
        """
        * Returns the associated intersector.

        :rtype: Geom2dHatch_Intersector

        """
        return _Geom2dHatch.Geom2dHatch_Hatcher_ChangeIntersector(self, *args)


    def Confusion2d(self, *args) -> "Standard_Real":
        """
        * Sets the confusion tolerance.

        :param Confusion:
        :type Confusion: float
        :rtype: None

        * Returns the 2d confusion tolerance, i.e. the value under which two points are considered identical in the parametric space of the hatching.

        :rtype: float

        """
        return _Geom2dHatch.Geom2dHatch_Hatcher_Confusion2d(self, *args)


    def Confusion3d(self, *args) -> "Standard_Real":
        """
        * Sets the confusion tolerance.

        :param Confusion:
        :type Confusion: float
        :rtype: None

        * Returns the 3d confusion tolerance, i.e. the value under which two points are considered identical in the 3d space of the hatching.

        :rtype: float

        """
        return _Geom2dHatch.Geom2dHatch_Hatcher_Confusion3d(self, *args)


    def KeepPoints(self, *args) -> "Standard_Boolean":
        """
        * Sets the above flag.

        :param Keep:
        :type Keep: bool
        :rtype: None

        * Returns the flag about the points consideration.

        :rtype: bool

        """
        return _Geom2dHatch.Geom2dHatch_Hatcher_KeepPoints(self, *args)


    def KeepSegments(self, *args) -> "Standard_Boolean":
        """
        * Sets the above flag.

        :param Keep:
        :type Keep: bool
        :rtype: None

        * Returns the flag about the segments consideration.

        :rtype: bool

        """
        return _Geom2dHatch.Geom2dHatch_Hatcher_KeepSegments(self, *args)


    def Clear(self, *args) -> "void":
        """
        * Removes all the hatchings and all the elements.

        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_Hatcher_Clear(self, *args)


    def ElementCurve(self, *args) -> "Geom2dAdaptor_Curve const &":
        """
        * Returns the curve associated to the IndE-th element.

        :param IndE:
        :type IndE: int
        :rtype: Geom2dAdaptor_Curve

        """
        return _Geom2dHatch.Geom2dHatch_Hatcher_ElementCurve(self, *args)


    def AddElement(self, *args) -> "Standard_Integer":
        """
        * Adds an element to the hatcher and returns its index.

        :param Curve:
        :type Curve: Geom2dAdaptor_Curve &
        :param Orientation: default value is TopAbs_FORWARD
        :type Orientation: TopAbs_Orientation
        :rtype: int

        """
        return _Geom2dHatch.Geom2dHatch_Hatcher_AddElement(self, *args)


    def RemElement(self, *args) -> "void":
        """
        * Removes the IndE-th element from the hatcher.

        :param IndE:
        :type IndE: int
        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_Hatcher_RemElement(self, *args)


    def ClrElements(self, *args) -> "void":
        """
        * Removes all the elements from the hatcher.

        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_Hatcher_ClrElements(self, *args)


    def HatchingCurve(self, *args) -> "Geom2dAdaptor_Curve const &":
        """
        * Returns the curve associated to the IndH-th hatching.

        :param IndH:
        :type IndH: int
        :rtype: Geom2dAdaptor_Curve

        """
        return _Geom2dHatch.Geom2dHatch_Hatcher_HatchingCurve(self, *args)


    def AddHatching(self, *args) -> "Standard_Integer":
        """
        * Adds a hatching to the hatcher and returns its index.

        :param Curve:
        :type Curve: Geom2dAdaptor_Curve &
        :rtype: int

        """
        return _Geom2dHatch.Geom2dHatch_Hatcher_AddHatching(self, *args)


    def RemHatching(self, *args) -> "void":
        """
        * Removes the IndH-th hatching from the hatcher.

        :param IndH:
        :type IndH: int
        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_Hatcher_RemHatching(self, *args)


    def ClrHatchings(self, *args) -> "void":
        """
        * Removes all the hatchings from the hatcher.

        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_Hatcher_ClrHatchings(self, *args)


    def NbPoints(self, *args) -> "Standard_Integer":
        """
        * Returns the number of intersection points of the IndH-th hatching.

        :param IndH:
        :type IndH: int
        :rtype: int

        """
        return _Geom2dHatch.Geom2dHatch_Hatcher_NbPoints(self, *args)


    def Point(self, *args) -> "HatchGen_PointOnHatching const &":
        """
        * Returns the IndP-th intersection point of the IndH-th hatching.

        :param IndH:
        :type IndH: int
        :param IndP:
        :type IndP: int
        :rtype: HatchGen_PointOnHatching

        """
        return _Geom2dHatch.Geom2dHatch_Hatcher_Point(self, *args)


    def Trim(self, *args) -> "void":
        """
        * Trims all the hatchings of the hatcher by all the elements of the hatcher.

        :rtype: None

        * Adds a hatching to the hatcher and trims it by the elements already given and returns its index.

        :param Curve:
        :type Curve: Geom2dAdaptor_Curve &
        :rtype: int

        * Trims the IndH-th hatching by the elements already given.

        :param IndH:
        :type IndH: int
        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_Hatcher_Trim(self, *args)


    def ComputeDomains(self, *args) -> "void":
        """
        * Computes the domains of all the hatchings.

        :rtype: None

        * Computes the domains of the IndH-th hatching.

        :param IndH:
        :type IndH: int
        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_Hatcher_ComputeDomains(self, *args)


    def TrimDone(self, *args) -> "Standard_Boolean":
        """
        * Returns the fact that the intersections were computed for the IndH-th hatching.

        :param IndH:
        :type IndH: int
        :rtype: bool

        """
        return _Geom2dHatch.Geom2dHatch_Hatcher_TrimDone(self, *args)


    def TrimFailed(self, *args) -> "Standard_Boolean":
        """
        * Returns the fact that the intersections failed for the IndH-th hatching.

        :param IndH:
        :type IndH: int
        :rtype: bool

        """
        return _Geom2dHatch.Geom2dHatch_Hatcher_TrimFailed(self, *args)


    def Status(self, *args) -> "HatchGen_ErrorStatus":
        """
        * Returns the status about the IndH-th hatching.

        :param IndH:
        :type IndH: int
        :rtype: HatchGen_ErrorStatus

        """
        return _Geom2dHatch.Geom2dHatch_Hatcher_Status(self, *args)


    def NbDomains(self, *args) -> "Standard_Integer":
        """
        * Returns the number of domains of the IndH-th hatching. Only ONE 'INFINITE' domain means that the hatching is fully included in the contour defined by the elements.

        :param IndH:
        :type IndH: int
        :rtype: int

        """
        return _Geom2dHatch.Geom2dHatch_Hatcher_NbDomains(self, *args)


    def Domain(self, *args) -> "HatchGen_Domain const &":
        """
        * Returns the IDom-th domain of the IndH-th hatching.

        :param IndH:
        :type IndH: int
        :param IDom:
        :type IDom: int
        :rtype: HatchGen_Domain

        """
        return _Geom2dHatch.Geom2dHatch_Hatcher_Domain(self, *args)


    def Dump(self, *args) -> "void":
        """
        * Dump the hatcher.

        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_Hatcher_Dump(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _Geom2dHatch.delete_Geom2dHatch_Hatcher
Geom2dHatch_Hatcher.Intersector = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatcher_Intersector, None, Geom2dHatch_Hatcher)
Geom2dHatch_Hatcher.ChangeIntersector = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatcher_ChangeIntersector, None, Geom2dHatch_Hatcher)
Geom2dHatch_Hatcher.Confusion2d = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatcher_Confusion2d, None, Geom2dHatch_Hatcher)
Geom2dHatch_Hatcher.Confusion3d = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatcher_Confusion3d, None, Geom2dHatch_Hatcher)
Geom2dHatch_Hatcher.KeepPoints = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatcher_KeepPoints, None, Geom2dHatch_Hatcher)
Geom2dHatch_Hatcher.KeepSegments = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatcher_KeepSegments, None, Geom2dHatch_Hatcher)
Geom2dHatch_Hatcher.Clear = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatcher_Clear, None, Geom2dHatch_Hatcher)
Geom2dHatch_Hatcher.ElementCurve = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatcher_ElementCurve, None, Geom2dHatch_Hatcher)
Geom2dHatch_Hatcher.AddElement = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatcher_AddElement, None, Geom2dHatch_Hatcher)
Geom2dHatch_Hatcher.RemElement = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatcher_RemElement, None, Geom2dHatch_Hatcher)
Geom2dHatch_Hatcher.ClrElements = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatcher_ClrElements, None, Geom2dHatch_Hatcher)
Geom2dHatch_Hatcher.HatchingCurve = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatcher_HatchingCurve, None, Geom2dHatch_Hatcher)
Geom2dHatch_Hatcher.AddHatching = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatcher_AddHatching, None, Geom2dHatch_Hatcher)
Geom2dHatch_Hatcher.RemHatching = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatcher_RemHatching, None, Geom2dHatch_Hatcher)
Geom2dHatch_Hatcher.ClrHatchings = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatcher_ClrHatchings, None, Geom2dHatch_Hatcher)
Geom2dHatch_Hatcher.NbPoints = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatcher_NbPoints, None, Geom2dHatch_Hatcher)
Geom2dHatch_Hatcher.Point = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatcher_Point, None, Geom2dHatch_Hatcher)
Geom2dHatch_Hatcher.Trim = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatcher_Trim, None, Geom2dHatch_Hatcher)
Geom2dHatch_Hatcher.ComputeDomains = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatcher_ComputeDomains, None, Geom2dHatch_Hatcher)
Geom2dHatch_Hatcher.TrimDone = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatcher_TrimDone, None, Geom2dHatch_Hatcher)
Geom2dHatch_Hatcher.TrimFailed = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatcher_TrimFailed, None, Geom2dHatch_Hatcher)
Geom2dHatch_Hatcher.Status = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatcher_Status, None, Geom2dHatch_Hatcher)
Geom2dHatch_Hatcher.NbDomains = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatcher_NbDomains, None, Geom2dHatch_Hatcher)
Geom2dHatch_Hatcher.Domain = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatcher_Domain, None, Geom2dHatch_Hatcher)
Geom2dHatch_Hatcher.Dump = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatcher_Dump, None, Geom2dHatch_Hatcher)
Geom2dHatch_Hatcher_swigregister = _Geom2dHatch.Geom2dHatch_Hatcher_swigregister
Geom2dHatch_Hatcher_swigregister(Geom2dHatch_Hatcher)

class Geom2dHatch_Hatching(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        * Creates a hatching.

        :param Curve:
        :type Curve: Geom2dAdaptor_Curve &
        :rtype: None

        """
        _Geom2dHatch.Geom2dHatch_Hatching_swiginit(self, _Geom2dHatch.new_Geom2dHatch_Hatching(*args))

    def Curve(self, *args) -> "Geom2dAdaptor_Curve const &":
        """
        * Returns the curve associated to the hatching.

        :rtype: Geom2dAdaptor_Curve

        """
        return _Geom2dHatch.Geom2dHatch_Hatching_Curve(self, *args)


    def ChangeCurve(self, *args) -> "Geom2dAdaptor_Curve &":
        """
        * Returns the curve associated to the hatching.

        :rtype: Geom2dAdaptor_Curve

        """
        return _Geom2dHatch.Geom2dHatch_Hatching_ChangeCurve(self, *args)


    def TrimDone(self, *args) -> "Standard_Boolean":
        """
        * Sets the flag about the trimming computations to the given value.

        :param Flag:
        :type Flag: bool
        :rtype: None

        * Returns the flag about the trimming computations.

        :rtype: bool

        """
        return _Geom2dHatch.Geom2dHatch_Hatching_TrimDone(self, *args)


    def TrimFailed(self, *args) -> "Standard_Boolean":
        """
        * Sets the flag about the trimming failure to the given value.

        :param Flag:
        :type Flag: bool
        :rtype: None

        * Returns the flag about the trimming failure.

        :rtype: bool

        """
        return _Geom2dHatch.Geom2dHatch_Hatching_TrimFailed(self, *args)


    def IsDone(self, *args) -> "Standard_Boolean":
        """
        * Sets the flag about the domains computation to the given value.

        :param Flag:
        :type Flag: bool
        :rtype: None

        * Returns the flag about the domains computation.

        :rtype: bool

        """
        return _Geom2dHatch.Geom2dHatch_Hatching_IsDone(self, *args)


    def Status(self, *args) -> "HatchGen_ErrorStatus":
        """
        * Sets the error status.

        :param Status:
        :type Status: HatchGen_ErrorStatus
        :rtype: None

        * Returns the error status.

        :rtype: HatchGen_ErrorStatus

        """
        return _Geom2dHatch.Geom2dHatch_Hatching_Status(self, *args)


    def AddPoint(self, *args) -> "void":
        """
        * Adds an intersection point to the hatching.

        :param Point:
        :type Point: HatchGen_PointOnHatching &
        :param Confusion:
        :type Confusion: float
        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_Hatching_AddPoint(self, *args)


    def NbPoints(self, *args) -> "Standard_Integer":
        """
        * Returns the number of intersection points of the hatching.

        :rtype: int

        """
        return _Geom2dHatch.Geom2dHatch_Hatching_NbPoints(self, *args)


    def Point(self, *args) -> "HatchGen_PointOnHatching const &":
        """
        * Returns the Index-th intersection point of the hatching. The exception OutOfRange is raised if Index < 1 or Index > NbPoints.

        :param Index:
        :type Index: int
        :rtype: HatchGen_PointOnHatching

        """
        return _Geom2dHatch.Geom2dHatch_Hatching_Point(self, *args)


    def ChangePoint(self, *args) -> "HatchGen_PointOnHatching &":
        """
        * Returns the Index-th intersection point of the hatching. The exception OutOfRange is raised if Index < 1 or Index > NbPoints.

        :param Index:
        :type Index: int
        :rtype: HatchGen_PointOnHatching

        """
        return _Geom2dHatch.Geom2dHatch_Hatching_ChangePoint(self, *args)


    def RemPoint(self, *args) -> "void":
        """
        * Removes the Index-th intersection point of the hatching. The exception OutOfRange is raised if Index < 1 or Index > NbPoints.

        :param Index:
        :type Index: int
        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_Hatching_RemPoint(self, *args)


    def ClrPoints(self, *args) -> "void":
        """
        * Removes all the intersection points of the hatching.

        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_Hatching_ClrPoints(self, *args)


    def AddDomain(self, *args) -> "void":
        """
        * Adds a domain to the hatching.

        :param Domain:
        :type Domain: HatchGen_Domain &
        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_Hatching_AddDomain(self, *args)


    def NbDomains(self, *args) -> "Standard_Integer":
        """
        * Returns the number of domains of the hatching.

        :rtype: int

        """
        return _Geom2dHatch.Geom2dHatch_Hatching_NbDomains(self, *args)


    def Domain(self, *args) -> "HatchGen_Domain const &":
        """
        * Returns the Index-th domain of the hatching. The exception OutOfRange is raised if Index < 1 or Index > NbDomains.

        :param Index:
        :type Index: int
        :rtype: HatchGen_Domain

        """
        return _Geom2dHatch.Geom2dHatch_Hatching_Domain(self, *args)


    def RemDomain(self, *args) -> "void":
        """
        * Removes the Index-th domain of the hatching. The exception OutOfRange is raised if Index < 1 or Index > NbDomains.

        :param Index:
        :type Index: int
        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_Hatching_RemDomain(self, *args)


    def ClrDomains(self, *args) -> "void":
        """
        * Removes all the domains of the hatching.

        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_Hatching_ClrDomains(self, *args)


    def ClassificationPoint(self, *args) -> "gp_Pnt2d":
        """
        * Returns a point on the curve. This point will be used for the classification.

        :rtype: gp_Pnt2d

        """
        return _Geom2dHatch.Geom2dHatch_Hatching_ClassificationPoint(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _Geom2dHatch.delete_Geom2dHatch_Hatching
Geom2dHatch_Hatching.Curve = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatching_Curve, None, Geom2dHatch_Hatching)
Geom2dHatch_Hatching.ChangeCurve = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatching_ChangeCurve, None, Geom2dHatch_Hatching)
Geom2dHatch_Hatching.TrimDone = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatching_TrimDone, None, Geom2dHatch_Hatching)
Geom2dHatch_Hatching.TrimFailed = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatching_TrimFailed, None, Geom2dHatch_Hatching)
Geom2dHatch_Hatching.IsDone = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatching_IsDone, None, Geom2dHatch_Hatching)
Geom2dHatch_Hatching.Status = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatching_Status, None, Geom2dHatch_Hatching)
Geom2dHatch_Hatching.AddPoint = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatching_AddPoint, None, Geom2dHatch_Hatching)
Geom2dHatch_Hatching.NbPoints = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatching_NbPoints, None, Geom2dHatch_Hatching)
Geom2dHatch_Hatching.Point = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatching_Point, None, Geom2dHatch_Hatching)
Geom2dHatch_Hatching.ChangePoint = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatching_ChangePoint, None, Geom2dHatch_Hatching)
Geom2dHatch_Hatching.RemPoint = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatching_RemPoint, None, Geom2dHatch_Hatching)
Geom2dHatch_Hatching.ClrPoints = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatching_ClrPoints, None, Geom2dHatch_Hatching)
Geom2dHatch_Hatching.AddDomain = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatching_AddDomain, None, Geom2dHatch_Hatching)
Geom2dHatch_Hatching.NbDomains = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatching_NbDomains, None, Geom2dHatch_Hatching)
Geom2dHatch_Hatching.Domain = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatching_Domain, None, Geom2dHatch_Hatching)
Geom2dHatch_Hatching.RemDomain = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatching_RemDomain, None, Geom2dHatch_Hatching)
Geom2dHatch_Hatching.ClrDomains = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatching_ClrDomains, None, Geom2dHatch_Hatching)
Geom2dHatch_Hatching.ClassificationPoint = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatching_ClassificationPoint, None, Geom2dHatch_Hatching)
Geom2dHatch_Hatching_swigregister = _Geom2dHatch.Geom2dHatch_Hatching_swigregister
Geom2dHatch_Hatching_swigregister(Geom2dHatch_Hatching)

class Geom2dHatch_Hatchings(OCC.TCollection.TCollection_BasicMap):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :param NbBuckets: default value is 1
        :type NbBuckets: int
        :rtype: None

        """
        _Geom2dHatch.Geom2dHatch_Hatchings_swiginit(self, _Geom2dHatch.new_Geom2dHatch_Hatchings(*args))

    def Assign(self, *args) -> "Geom2dHatch_Hatchings &":
        """
        :param Other:
        :type Other: Geom2dHatch_Hatchings &
        :rtype: Geom2dHatch_Hatchings

        """
        return _Geom2dHatch.Geom2dHatch_Hatchings_Assign(self, *args)


    def Set(self, *args) -> "Geom2dHatch_Hatchings &":
        """
        :param Other:
        :type Other: Geom2dHatch_Hatchings &
        :rtype: Geom2dHatch_Hatchings

        """
        return _Geom2dHatch.Geom2dHatch_Hatchings_Set(self, *args)


    def ReSize(self, *args) -> "void":
        """
        :param NbBuckets:
        :type NbBuckets: int
        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_Hatchings_ReSize(self, *args)


    def Clear(self, *args) -> "void":
        """
        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_Hatchings_Clear(self, *args)


    def Bind(self, *args) -> "Standard_Boolean":
        """
        :param K:
        :type K: int &
        :param I:
        :type I: Geom2dHatch_Hatching &
        :rtype: bool

        """
        return _Geom2dHatch.Geom2dHatch_Hatchings_Bind(self, *args)


    def IsBound(self, *args) -> "Standard_Boolean":
        """
        :param K:
        :type K: int &
        :rtype: bool

        """
        return _Geom2dHatch.Geom2dHatch_Hatchings_IsBound(self, *args)


    def UnBind(self, *args) -> "Standard_Boolean":
        """
        :param K:
        :type K: int &
        :rtype: bool

        """
        return _Geom2dHatch.Geom2dHatch_Hatchings_UnBind(self, *args)


    def Find(self, *args) -> "Geom2dHatch_Hatching const &":
        """
        :param K:
        :type K: int &
        :rtype: Geom2dHatch_Hatching

        """
        return _Geom2dHatch.Geom2dHatch_Hatchings_Find(self, *args)


    def ChangeFind(self, *args) -> "Geom2dHatch_Hatching &":
        """
        :param K:
        :type K: int &
        :rtype: Geom2dHatch_Hatching

        """
        return _Geom2dHatch.Geom2dHatch_Hatchings_ChangeFind(self, *args)


    def Find1(self, *args) -> "Standard_Address":
        """
        :param K:
        :type K: int &
        :rtype: Standard_Address

        """
        return _Geom2dHatch.Geom2dHatch_Hatchings_Find1(self, *args)


    def ChangeFind1(self, *args) -> "Standard_Address":
        """
        :param K:
        :type K: int &
        :rtype: Standard_Address

        """
        return _Geom2dHatch.Geom2dHatch_Hatchings_ChangeFind1(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _Geom2dHatch.delete_Geom2dHatch_Hatchings
Geom2dHatch_Hatchings.Assign = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatchings_Assign, None, Geom2dHatch_Hatchings)
Geom2dHatch_Hatchings.Set = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatchings_Set, None, Geom2dHatch_Hatchings)
Geom2dHatch_Hatchings.ReSize = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatchings_ReSize, None, Geom2dHatch_Hatchings)
Geom2dHatch_Hatchings.Clear = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatchings_Clear, None, Geom2dHatch_Hatchings)
Geom2dHatch_Hatchings.Bind = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatchings_Bind, None, Geom2dHatch_Hatchings)
Geom2dHatch_Hatchings.IsBound = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatchings_IsBound, None, Geom2dHatch_Hatchings)
Geom2dHatch_Hatchings.UnBind = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatchings_UnBind, None, Geom2dHatch_Hatchings)
Geom2dHatch_Hatchings.Find = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatchings_Find, None, Geom2dHatch_Hatchings)
Geom2dHatch_Hatchings.ChangeFind = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatchings_ChangeFind, None, Geom2dHatch_Hatchings)
Geom2dHatch_Hatchings.Find1 = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatchings_Find1, None, Geom2dHatch_Hatchings)
Geom2dHatch_Hatchings.ChangeFind1 = new_instancemethod(_Geom2dHatch.Geom2dHatch_Hatchings_ChangeFind1, None, Geom2dHatch_Hatchings)
Geom2dHatch_Hatchings_swigregister = _Geom2dHatch.Geom2dHatch_Hatchings_swigregister
Geom2dHatch_Hatchings_swigregister(Geom2dHatch_Hatchings)

class Geom2dHatch_Intersector(OCC.Geom2dInt.Geom2dInt_GInter):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def ConfusionTolerance(self, *args) -> "Standard_Real":
        """
        * Returns the confusion tolerance of the intersector.

        :rtype: float

        """
        return _Geom2dHatch.Geom2dHatch_Intersector_ConfusionTolerance(self, *args)


    def SetConfusionTolerance(self, *args) -> "void":
        """
        * Sets the confusion tolerance of the intersector.

        :param Confusion:
        :type Confusion: float
        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_Intersector_SetConfusionTolerance(self, *args)


    def TangencyTolerance(self, *args) -> "Standard_Real":
        """
        * Returns the tangency tolerance of the intersector.

        :rtype: float

        """
        return _Geom2dHatch.Geom2dHatch_Intersector_TangencyTolerance(self, *args)


    def SetTangencyTolerance(self, *args) -> "void":
        """
        * Sets the tangency tolerance of the intersector.

        :param Tangency:
        :type Tangency: float
        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_Intersector_SetTangencyTolerance(self, *args)


    def Intersect(self, *args) -> "void":
        """
        * Intersects the curves C1 and C2. The results are retreived by the usual methods described in IntRes2d_Intersection. Creates an intersector.

        :param C1:
        :type C1: Geom2dAdaptor_Curve &
        :param C2:
        :type C2: Geom2dAdaptor_Curve &
        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_Intersector_Intersect(self, *args)


    def __init__(self, *args):
        """
        * Creates an intersector.

        :param Confusion:
        :type Confusion: float
        :param Tangency:
        :type Tangency: float
        :rtype: None

        :rtype: None

        """
        _Geom2dHatch.Geom2dHatch_Intersector_swiginit(self, _Geom2dHatch.new_Geom2dHatch_Intersector(*args))

    def Perform(self, *args) -> "void":
        """
        * Performs the intersection between the 2d line segment (<L>, <P>) and the Curve <E>. The line segment is the part of the 2d line <L> of parameter range [0, <P>] (P is positive and can be RealLast()). Tol is the Tolerance on the segment. The order is relevant, the first argument is the segment, the second the Edge.

        :param L:
        :type L: gp_Lin2d
        :param P:
        :type P: float
        :param Tol:
        :type Tol: float
        :param E:
        :type E: Geom2dAdaptor_Curve &
        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_Intersector_Perform(self, *args)


    def LocalGeometry(self, *args) -> "void":
        """
        * Returns in <T>, <N> and <C> the tangent, normal and curvature of the edge <E> at parameter value <U>.

        :param E:
        :type E: Geom2dAdaptor_Curve &
        :param U:
        :type U: float
        :param T:
        :type T: gp_Dir2d
        :param N:
        :type N: gp_Dir2d
        :param C:
        :type C: float &
        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_Intersector_LocalGeometry(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _Geom2dHatch.delete_Geom2dHatch_Intersector
Geom2dHatch_Intersector.ConfusionTolerance = new_instancemethod(_Geom2dHatch.Geom2dHatch_Intersector_ConfusionTolerance, None, Geom2dHatch_Intersector)
Geom2dHatch_Intersector.SetConfusionTolerance = new_instancemethod(_Geom2dHatch.Geom2dHatch_Intersector_SetConfusionTolerance, None, Geom2dHatch_Intersector)
Geom2dHatch_Intersector.TangencyTolerance = new_instancemethod(_Geom2dHatch.Geom2dHatch_Intersector_TangencyTolerance, None, Geom2dHatch_Intersector)
Geom2dHatch_Intersector.SetTangencyTolerance = new_instancemethod(_Geom2dHatch.Geom2dHatch_Intersector_SetTangencyTolerance, None, Geom2dHatch_Intersector)
Geom2dHatch_Intersector.Intersect = new_instancemethod(_Geom2dHatch.Geom2dHatch_Intersector_Intersect, None, Geom2dHatch_Intersector)
Geom2dHatch_Intersector.Perform = new_instancemethod(_Geom2dHatch.Geom2dHatch_Intersector_Perform, None, Geom2dHatch_Intersector)
Geom2dHatch_Intersector.LocalGeometry = new_instancemethod(_Geom2dHatch.Geom2dHatch_Intersector_LocalGeometry, None, Geom2dHatch_Intersector)
Geom2dHatch_Intersector_swigregister = _Geom2dHatch.Geom2dHatch_Intersector_swigregister
Geom2dHatch_Intersector_swigregister(Geom2dHatch_Intersector)

class Geom2dHatch_MapOfElements(OCC.TCollection.TCollection_BasicMap):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :param NbBuckets: default value is 1
        :type NbBuckets: int
        :rtype: None

        """
        _Geom2dHatch.Geom2dHatch_MapOfElements_swiginit(self, _Geom2dHatch.new_Geom2dHatch_MapOfElements(*args))

    def Assign(self, *args) -> "Geom2dHatch_MapOfElements &":
        """
        :param Other:
        :type Other: Geom2dHatch_MapOfElements &
        :rtype: Geom2dHatch_MapOfElements

        """
        return _Geom2dHatch.Geom2dHatch_MapOfElements_Assign(self, *args)


    def Set(self, *args) -> "Geom2dHatch_MapOfElements &":
        """
        :param Other:
        :type Other: Geom2dHatch_MapOfElements &
        :rtype: Geom2dHatch_MapOfElements

        """
        return _Geom2dHatch.Geom2dHatch_MapOfElements_Set(self, *args)


    def ReSize(self, *args) -> "void":
        """
        :param NbBuckets:
        :type NbBuckets: int
        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_MapOfElements_ReSize(self, *args)


    def Clear(self, *args) -> "void":
        """
        :rtype: None

        """
        return _Geom2dHatch.Geom2dHatch_MapOfElements_Clear(self, *args)


    def Bind(self, *args) -> "Standard_Boolean":
        """
        :param K:
        :type K: int &
        :param I:
        :type I: Geom2dHatch_Element &
        :rtype: bool

        """
        return _Geom2dHatch.Geom2dHatch_MapOfElements_Bind(self, *args)


    def IsBound(self, *args) -> "Standard_Boolean":
        """
        :param K:
        :type K: int &
        :rtype: bool

        """
        return _Geom2dHatch.Geom2dHatch_MapOfElements_IsBound(self, *args)


    def UnBind(self, *args) -> "Standard_Boolean":
        """
        :param K:
        :type K: int &
        :rtype: bool

        """
        return _Geom2dHatch.Geom2dHatch_MapOfElements_UnBind(self, *args)


    def Find(self, *args) -> "Geom2dHatch_Element const &":
        """
        :param K:
        :type K: int &
        :rtype: Geom2dHatch_Element

        """
        return _Geom2dHatch.Geom2dHatch_MapOfElements_Find(self, *args)


    def ChangeFind(self, *args) -> "Geom2dHatch_Element &":
        """
        :param K:
        :type K: int &
        :rtype: Geom2dHatch_Element

        """
        return _Geom2dHatch.Geom2dHatch_MapOfElements_ChangeFind(self, *args)


    def Find1(self, *args) -> "Standard_Address":
        """
        :param K:
        :type K: int &
        :rtype: Standard_Address

        """
        return _Geom2dHatch.Geom2dHatch_MapOfElements_Find1(self, *args)


    def ChangeFind1(self, *args) -> "Standard_Address":
        """
        :param K:
        :type K: int &
        :rtype: Standard_Address

        """
        return _Geom2dHatch.Geom2dHatch_MapOfElements_ChangeFind1(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _Geom2dHatch.delete_Geom2dHatch_MapOfElements
Geom2dHatch_MapOfElements.Assign = new_instancemethod(_Geom2dHatch.Geom2dHatch_MapOfElements_Assign, None, Geom2dHatch_MapOfElements)
Geom2dHatch_MapOfElements.Set = new_instancemethod(_Geom2dHatch.Geom2dHatch_MapOfElements_Set, None, Geom2dHatch_MapOfElements)
Geom2dHatch_MapOfElements.ReSize = new_instancemethod(_Geom2dHatch.Geom2dHatch_MapOfElements_ReSize, None, Geom2dHatch_MapOfElements)
Geom2dHatch_MapOfElements.Clear = new_instancemethod(_Geom2dHatch.Geom2dHatch_MapOfElements_Clear, None, Geom2dHatch_MapOfElements)
Geom2dHatch_MapOfElements.Bind = new_instancemethod(_Geom2dHatch.Geom2dHatch_MapOfElements_Bind, None, Geom2dHatch_MapOfElements)
Geom2dHatch_MapOfElements.IsBound = new_instancemethod(_Geom2dHatch.Geom2dHatch_MapOfElements_IsBound, None, Geom2dHatch_MapOfElements)
Geom2dHatch_MapOfElements.UnBind = new_instancemethod(_Geom2dHatch.Geom2dHatch_MapOfElements_UnBind, None, Geom2dHatch_MapOfElements)
Geom2dHatch_MapOfElements.Find = new_instancemethod(_Geom2dHatch.Geom2dHatch_MapOfElements_Find, None, Geom2dHatch_MapOfElements)
Geom2dHatch_MapOfElements.ChangeFind = new_instancemethod(_Geom2dHatch.Geom2dHatch_MapOfElements_ChangeFind, None, Geom2dHatch_MapOfElements)
Geom2dHatch_MapOfElements.Find1 = new_instancemethod(_Geom2dHatch.Geom2dHatch_MapOfElements_Find1, None, Geom2dHatch_MapOfElements)
Geom2dHatch_MapOfElements.ChangeFind1 = new_instancemethod(_Geom2dHatch.Geom2dHatch_MapOfElements_ChangeFind1, None, Geom2dHatch_MapOfElements)
Geom2dHatch_MapOfElements_swigregister = _Geom2dHatch.Geom2dHatch_MapOfElements_swigregister
Geom2dHatch_MapOfElements_swigregister(Geom2dHatch_MapOfElements)



