# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _RWStepAP214.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_RWStepAP214')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_RWStepAP214')
    _RWStepAP214 = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_RWStepAP214', [dirname(__file__)])
        except ImportError:
            import _RWStepAP214
            return _RWStepAP214
        try:
            _mod = imp.load_module('_RWStepAP214', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _RWStepAP214 = swig_import_helper()
    del swig_import_helper
else:
    import _RWStepAP214
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


class SwigPyIterator(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _RWStepAP214.delete_SwigPyIterator
    def __iter__(self):
        return self
SwigPyIterator.value = new_instancemethod(_RWStepAP214.SwigPyIterator_value, None, SwigPyIterator)
SwigPyIterator.incr = new_instancemethod(_RWStepAP214.SwigPyIterator_incr, None, SwigPyIterator)
SwigPyIterator.decr = new_instancemethod(_RWStepAP214.SwigPyIterator_decr, None, SwigPyIterator)
SwigPyIterator.distance = new_instancemethod(_RWStepAP214.SwigPyIterator_distance, None, SwigPyIterator)
SwigPyIterator.equal = new_instancemethod(_RWStepAP214.SwigPyIterator_equal, None, SwigPyIterator)
SwigPyIterator.copy = new_instancemethod(_RWStepAP214.SwigPyIterator_copy, None, SwigPyIterator)
SwigPyIterator.next = new_instancemethod(_RWStepAP214.SwigPyIterator_next, None, SwigPyIterator)
SwigPyIterator.__next__ = new_instancemethod(_RWStepAP214.SwigPyIterator___next__, None, SwigPyIterator)
SwigPyIterator.previous = new_instancemethod(_RWStepAP214.SwigPyIterator_previous, None, SwigPyIterator)
SwigPyIterator.advance = new_instancemethod(_RWStepAP214.SwigPyIterator_advance, None, SwigPyIterator)
SwigPyIterator.__eq__ = new_instancemethod(_RWStepAP214.SwigPyIterator___eq__, None, SwigPyIterator)
SwigPyIterator.__ne__ = new_instancemethod(_RWStepAP214.SwigPyIterator___ne__, None, SwigPyIterator)
SwigPyIterator.__iadd__ = new_instancemethod(_RWStepAP214.SwigPyIterator___iadd__, None, SwigPyIterator)
SwigPyIterator.__isub__ = new_instancemethod(_RWStepAP214.SwigPyIterator___isub__, None, SwigPyIterator)
SwigPyIterator.__add__ = new_instancemethod(_RWStepAP214.SwigPyIterator___add__, None, SwigPyIterator)
SwigPyIterator.__sub__ = new_instancemethod(_RWStepAP214.SwigPyIterator___sub__, None, SwigPyIterator)
SwigPyIterator_swigregister = _RWStepAP214.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)


def _dumps_object(klass):
    """ Improve string output for any oce object.
    By default, __repr__ method returns something like:
    <OCC.TopoDS.TopoDS_Shape; proxy of <Swig Object of type 'TopoDS_Shape *' at 0x02BB0758> >
    This is too much verbose.
    We prefer :
    class<'gp_Pnt'>
    or
    class<'TopoDS_Shape'; Type:Solid; Id:59391729>
    """
    klass_name = str(klass.__class__).split(".")[2].split("'")[0]
    repr_string = "class<'" + klass_name + "'"
# for TopoDS_Shape, we also look for the base type
    if klass_name == "TopoDS_Shape":
        st = klass.ShapeType()
        types = {OCC.TopAbs.TopAbs_VERTEX:"Vertex",
                 OCC.TopAbs.TopAbs_SOLID:"Solid",
                 OCC.TopAbs.TopAbs_EDGE:"Edge",
                 OCC.TopAbs.TopAbs_FACE:"Face",
                 OCC.TopAbs.TopAbs_SHELL:"Shell",
                 OCC.TopAbs.TopAbs_WIRE:"Wire",
                 OCC.TopAbs.TopAbs_COMPOUND:"Compound",
                 OCC.TopAbs.TopAbs_COMPSOLID:"Compsolid."}
        repr_string += "; Type:%s" % types[st]        
# for each class that has an HashCode method define,
# print the id
    if hasattr(klass, "HashCode"):
        klass_id = hash(klass)
        repr_string += "; id:%s" % klass_id
    repr_string += ">"
    return repr_string

import OCC.Standard
import OCC.Interface
import OCC.TCollection
import OCC.MMgt
import OCC.TColStd
import OCC.Message
import OCC.StepAP214
import OCC.StepBasic
import OCC.StepRepr
import OCC.StepShape
import OCC.StepGeom

def register_handle(handle, base_object):
    """
    Inserts the handle into the base object to
    prevent memory corruption in certain cases
    """
    try:
        if base_object.IsKind("Standard_Transient"):
            base_object.thisHandle = handle
            base_object.thisown = False
    except:
        pass

class rwstepap214(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def Init(*args) -> "void":
        """
        * enforced the initialisation of the libraries

        :rtype: void

        """
        return _RWStepAP214.rwstepap214_Init(*args)

    Init = staticmethod(Init)

    __repr__ = _dumps_object


    def __init__(self):
        _RWStepAP214.rwstepap214_swiginit(self, _RWStepAP214.new_rwstepap214())
    __swig_destroy__ = _RWStepAP214.delete_rwstepap214
rwstepap214_swigregister = _RWStepAP214.rwstepap214_swigregister
rwstepap214_swigregister(rwstepap214)

def rwstepap214_Init(*args) -> "void":
    """
    * enforced the initialisation of the libraries

    :rtype: void

    """
    return _RWStepAP214.rwstepap214_Init(*args)

class RWStepAP214_GeneralModule(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        * Creates a GeneralModule

        :rtype: None

        """
        _RWStepAP214.RWStepAP214_GeneralModule_swiginit(self, _RWStepAP214.new_RWStepAP214_GeneralModule(*args))

    def FillSharedCase(self, *args) -> "void":
        """
        * Specific filling of the list of Entities shared by an Entity <ent>, according to a Case Number <CN> (provided by StepAP214 Protocol).

        :param CN:
        :type CN: int
        :param ent:
        :type ent: Handle_Standard_Transient &
        :param iter:
        :type iter: Interface_EntityIterator &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_GeneralModule_FillSharedCase(self, *args)


    def CheckCase(self, *args) -> "void":
        """
        * Specific Checking of an Entity <ent>

        :param CN:
        :type CN: int
        :param ent:
        :type ent: Handle_Standard_Transient &
        :param shares:
        :type shares: Interface_ShareTool &
        :param ach:
        :type ach: Handle_Interface_Check &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_GeneralModule_CheckCase(self, *args)


    def CopyCase(self, *args) -> "void":
        """
        * Specific Copy ('Deep') from <entfrom> to <entto> (same type) by using a CopyTool which provides its working Map. Use method Transferred from CopyTool to work

        :param CN:
        :type CN: int
        :param entfrom:
        :type entfrom: Handle_Standard_Transient &
        :param entto:
        :type entto: Handle_Standard_Transient &
        :param TC:
        :type TC: Interface_CopyTool &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_GeneralModule_CopyCase(self, *args)


    def NewVoid(self, *args) -> "Standard_Boolean":
        """
        :param CN:
        :type CN: int
        :param ent:
        :type ent: Handle_Standard_Transient &
        :rtype: bool

        """
        return _RWStepAP214.RWStepAP214_GeneralModule_NewVoid(self, *args)


    def CategoryNumber(self, *args) -> "Standard_Integer":
        """
        :param CN:
        :type CN: int
        :param ent:
        :type ent: Handle_Standard_Transient &
        :param shares:
        :type shares: Interface_ShareTool &
        :rtype: int

        """
        return _RWStepAP214.RWStepAP214_GeneralModule_CategoryNumber(self, *args)


    def Name(self, *args) -> "Handle_TCollection_HAsciiString":
        """
        * Returns the name of a STEP Entity according to its type

        :param CN:
        :type CN: int
        :param ent:
        :type ent: Handle_Standard_Transient &
        :param shares:
        :type shares: Interface_ShareTool &
        :rtype: Handle_TCollection_HAsciiString

        """
        return _RWStepAP214.RWStepAP214_GeneralModule_Name(self, *args)


    def GetHandle(self):
        try:
            return self.thisHandle
        except:
            self.thisHandle = Handle_RWStepAP214_GeneralModule(self)
            self.thisown = False
            return self.thisHandle


    __repr__ = _dumps_object

    __swig_destroy__ = _RWStepAP214.delete_RWStepAP214_GeneralModule
RWStepAP214_GeneralModule.FillSharedCase = new_instancemethod(_RWStepAP214.RWStepAP214_GeneralModule_FillSharedCase, None, RWStepAP214_GeneralModule)
RWStepAP214_GeneralModule.CheckCase = new_instancemethod(_RWStepAP214.RWStepAP214_GeneralModule_CheckCase, None, RWStepAP214_GeneralModule)
RWStepAP214_GeneralModule.CopyCase = new_instancemethod(_RWStepAP214.RWStepAP214_GeneralModule_CopyCase, None, RWStepAP214_GeneralModule)
RWStepAP214_GeneralModule.NewVoid = new_instancemethod(_RWStepAP214.RWStepAP214_GeneralModule_NewVoid, None, RWStepAP214_GeneralModule)
RWStepAP214_GeneralModule.CategoryNumber = new_instancemethod(_RWStepAP214.RWStepAP214_GeneralModule_CategoryNumber, None, RWStepAP214_GeneralModule)
RWStepAP214_GeneralModule.Name = new_instancemethod(_RWStepAP214.RWStepAP214_GeneralModule_Name, None, RWStepAP214_GeneralModule)
RWStepAP214_GeneralModule_swigregister = _RWStepAP214.RWStepAP214_GeneralModule_swigregister
RWStepAP214_GeneralModule_swigregister(RWStepAP214_GeneralModule)

class Handle_RWStepAP214_GeneralModule(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        _RWStepAP214.Handle_RWStepAP214_GeneralModule_swiginit(self, _RWStepAP214.new_Handle_RWStepAP214_GeneralModule(*args))

            # register the handle in the base object
        if len(args) > 0:
            register_handle(self, args[0])



    DownCast = staticmethod(_RWStepAP214.Handle_RWStepAP214_GeneralModule_DownCast)

    def GetObject(self):
        obj = self._get_reference()
        register_handle(self, obj)
        return obj

    __swig_destroy__ = _RWStepAP214.delete_Handle_RWStepAP214_GeneralModule
Handle_RWStepAP214_GeneralModule.Nullify = new_instancemethod(_RWStepAP214.Handle_RWStepAP214_GeneralModule_Nullify, None, Handle_RWStepAP214_GeneralModule)
Handle_RWStepAP214_GeneralModule.IsNull = new_instancemethod(_RWStepAP214.Handle_RWStepAP214_GeneralModule_IsNull, None, Handle_RWStepAP214_GeneralModule)
Handle_RWStepAP214_GeneralModule._get_reference = new_instancemethod(_RWStepAP214.Handle_RWStepAP214_GeneralModule__get_reference, None, Handle_RWStepAP214_GeneralModule)
Handle_RWStepAP214_GeneralModule_swigregister = _RWStepAP214.Handle_RWStepAP214_GeneralModule_swigregister
Handle_RWStepAP214_GeneralModule_swigregister(Handle_RWStepAP214_GeneralModule)

def Handle_RWStepAP214_GeneralModule_DownCast(AnObject: 'Handle_Standard_Transient') -> "Handle_RWStepAP214_GeneralModule const":
    return _RWStepAP214.Handle_RWStepAP214_GeneralModule_DownCast(AnObject)
Handle_RWStepAP214_GeneralModule_DownCast = _RWStepAP214.Handle_RWStepAP214_GeneralModule_DownCast

class RWStepAP214_RWAppliedApprovalAssignment(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        """
        _RWStepAP214.RWStepAP214_RWAppliedApprovalAssignment_swiginit(self, _RWStepAP214.new_RWStepAP214_RWAppliedApprovalAssignment(*args))

    def ReadStep(self, *args) -> "void":
        """
        :param data:
        :type data: Handle_StepData_StepReaderData &
        :param num:
        :type num: int
        :param ach:
        :type ach: Handle_Interface_Check &
        :param ent:
        :type ent: Handle_StepAP214_AppliedApprovalAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAppliedApprovalAssignment_ReadStep(self, *args)


    def WriteStep(self, *args) -> "void":
        """
        :param SW:
        :type SW: StepData_StepWriter &
        :param ent:
        :type ent: Handle_StepAP214_AppliedApprovalAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAppliedApprovalAssignment_WriteStep(self, *args)


    def Share(self, *args) -> "void":
        """
        :param ent:
        :type ent: Handle_StepAP214_AppliedApprovalAssignment &
        :param iter:
        :type iter: Interface_EntityIterator &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAppliedApprovalAssignment_Share(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _RWStepAP214.delete_RWStepAP214_RWAppliedApprovalAssignment
RWStepAP214_RWAppliedApprovalAssignment.ReadStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAppliedApprovalAssignment_ReadStep, None, RWStepAP214_RWAppliedApprovalAssignment)
RWStepAP214_RWAppliedApprovalAssignment.WriteStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAppliedApprovalAssignment_WriteStep, None, RWStepAP214_RWAppliedApprovalAssignment)
RWStepAP214_RWAppliedApprovalAssignment.Share = new_instancemethod(_RWStepAP214.RWStepAP214_RWAppliedApprovalAssignment_Share, None, RWStepAP214_RWAppliedApprovalAssignment)
RWStepAP214_RWAppliedApprovalAssignment_swigregister = _RWStepAP214.RWStepAP214_RWAppliedApprovalAssignment_swigregister
RWStepAP214_RWAppliedApprovalAssignment_swigregister(RWStepAP214_RWAppliedApprovalAssignment)

class RWStepAP214_RWAppliedDateAndTimeAssignment(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        """
        _RWStepAP214.RWStepAP214_RWAppliedDateAndTimeAssignment_swiginit(self, _RWStepAP214.new_RWStepAP214_RWAppliedDateAndTimeAssignment(*args))

    def ReadStep(self, *args) -> "void":
        """
        :param data:
        :type data: Handle_StepData_StepReaderData &
        :param num:
        :type num: int
        :param ach:
        :type ach: Handle_Interface_Check &
        :param ent:
        :type ent: Handle_StepAP214_AppliedDateAndTimeAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAppliedDateAndTimeAssignment_ReadStep(self, *args)


    def WriteStep(self, *args) -> "void":
        """
        :param SW:
        :type SW: StepData_StepWriter &
        :param ent:
        :type ent: Handle_StepAP214_AppliedDateAndTimeAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAppliedDateAndTimeAssignment_WriteStep(self, *args)


    def Share(self, *args) -> "void":
        """
        :param ent:
        :type ent: Handle_StepAP214_AppliedDateAndTimeAssignment &
        :param iter:
        :type iter: Interface_EntityIterator &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAppliedDateAndTimeAssignment_Share(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _RWStepAP214.delete_RWStepAP214_RWAppliedDateAndTimeAssignment
RWStepAP214_RWAppliedDateAndTimeAssignment.ReadStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAppliedDateAndTimeAssignment_ReadStep, None, RWStepAP214_RWAppliedDateAndTimeAssignment)
RWStepAP214_RWAppliedDateAndTimeAssignment.WriteStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAppliedDateAndTimeAssignment_WriteStep, None, RWStepAP214_RWAppliedDateAndTimeAssignment)
RWStepAP214_RWAppliedDateAndTimeAssignment.Share = new_instancemethod(_RWStepAP214.RWStepAP214_RWAppliedDateAndTimeAssignment_Share, None, RWStepAP214_RWAppliedDateAndTimeAssignment)
RWStepAP214_RWAppliedDateAndTimeAssignment_swigregister = _RWStepAP214.RWStepAP214_RWAppliedDateAndTimeAssignment_swigregister
RWStepAP214_RWAppliedDateAndTimeAssignment_swigregister(RWStepAP214_RWAppliedDateAndTimeAssignment)

class RWStepAP214_RWAppliedDateAssignment(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        """
        _RWStepAP214.RWStepAP214_RWAppliedDateAssignment_swiginit(self, _RWStepAP214.new_RWStepAP214_RWAppliedDateAssignment(*args))

    def ReadStep(self, *args) -> "void":
        """
        :param data:
        :type data: Handle_StepData_StepReaderData &
        :param num:
        :type num: int
        :param ach:
        :type ach: Handle_Interface_Check &
        :param ent:
        :type ent: Handle_StepAP214_AppliedDateAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAppliedDateAssignment_ReadStep(self, *args)


    def WriteStep(self, *args) -> "void":
        """
        :param SW:
        :type SW: StepData_StepWriter &
        :param ent:
        :type ent: Handle_StepAP214_AppliedDateAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAppliedDateAssignment_WriteStep(self, *args)


    def Share(self, *args) -> "void":
        """
        :param ent:
        :type ent: Handle_StepAP214_AppliedDateAssignment &
        :param iter:
        :type iter: Interface_EntityIterator &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAppliedDateAssignment_Share(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _RWStepAP214.delete_RWStepAP214_RWAppliedDateAssignment
RWStepAP214_RWAppliedDateAssignment.ReadStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAppliedDateAssignment_ReadStep, None, RWStepAP214_RWAppliedDateAssignment)
RWStepAP214_RWAppliedDateAssignment.WriteStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAppliedDateAssignment_WriteStep, None, RWStepAP214_RWAppliedDateAssignment)
RWStepAP214_RWAppliedDateAssignment.Share = new_instancemethod(_RWStepAP214.RWStepAP214_RWAppliedDateAssignment_Share, None, RWStepAP214_RWAppliedDateAssignment)
RWStepAP214_RWAppliedDateAssignment_swigregister = _RWStepAP214.RWStepAP214_RWAppliedDateAssignment_swigregister
RWStepAP214_RWAppliedDateAssignment_swigregister(RWStepAP214_RWAppliedDateAssignment)

class RWStepAP214_RWAppliedDocumentReference(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        """
        _RWStepAP214.RWStepAP214_RWAppliedDocumentReference_swiginit(self, _RWStepAP214.new_RWStepAP214_RWAppliedDocumentReference(*args))

    def ReadStep(self, *args) -> "void":
        """
        :param data:
        :type data: Handle_StepData_StepReaderData &
        :param num:
        :type num: int
        :param ach:
        :type ach: Handle_Interface_Check &
        :param ent:
        :type ent: Handle_StepAP214_AppliedDocumentReference &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAppliedDocumentReference_ReadStep(self, *args)


    def WriteStep(self, *args) -> "void":
        """
        :param SW:
        :type SW: StepData_StepWriter &
        :param ent:
        :type ent: Handle_StepAP214_AppliedDocumentReference &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAppliedDocumentReference_WriteStep(self, *args)


    def Share(self, *args) -> "void":
        """
        :param ent:
        :type ent: Handle_StepAP214_AppliedDocumentReference &
        :param iter:
        :type iter: Interface_EntityIterator &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAppliedDocumentReference_Share(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _RWStepAP214.delete_RWStepAP214_RWAppliedDocumentReference
RWStepAP214_RWAppliedDocumentReference.ReadStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAppliedDocumentReference_ReadStep, None, RWStepAP214_RWAppliedDocumentReference)
RWStepAP214_RWAppliedDocumentReference.WriteStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAppliedDocumentReference_WriteStep, None, RWStepAP214_RWAppliedDocumentReference)
RWStepAP214_RWAppliedDocumentReference.Share = new_instancemethod(_RWStepAP214.RWStepAP214_RWAppliedDocumentReference_Share, None, RWStepAP214_RWAppliedDocumentReference)
RWStepAP214_RWAppliedDocumentReference_swigregister = _RWStepAP214.RWStepAP214_RWAppliedDocumentReference_swigregister
RWStepAP214_RWAppliedDocumentReference_swigregister(RWStepAP214_RWAppliedDocumentReference)

class RWStepAP214_RWAppliedExternalIdentificationAssignment(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        * Empty constructor

        :rtype: None

        """
        _RWStepAP214.RWStepAP214_RWAppliedExternalIdentificationAssignment_swiginit(self, _RWStepAP214.new_RWStepAP214_RWAppliedExternalIdentificationAssignment(*args))

    def ReadStep(self, *args) -> "void":
        """
        * Reads AppliedExternalIdentificationAssignment

        :param data:
        :type data: Handle_StepData_StepReaderData &
        :param num:
        :type num: int
        :param ach:
        :type ach: Handle_Interface_Check &
        :param ent:
        :type ent: Handle_StepAP214_AppliedExternalIdentificationAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAppliedExternalIdentificationAssignment_ReadStep(self, *args)


    def WriteStep(self, *args) -> "void":
        """
        * Writes AppliedExternalIdentificationAssignment

        :param SW:
        :type SW: StepData_StepWriter &
        :param ent:
        :type ent: Handle_StepAP214_AppliedExternalIdentificationAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAppliedExternalIdentificationAssignment_WriteStep(self, *args)


    def Share(self, *args) -> "void":
        """
        * Fills data for graph (shared items)

        :param ent:
        :type ent: Handle_StepAP214_AppliedExternalIdentificationAssignment &
        :param iter:
        :type iter: Interface_EntityIterator &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAppliedExternalIdentificationAssignment_Share(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _RWStepAP214.delete_RWStepAP214_RWAppliedExternalIdentificationAssignment
RWStepAP214_RWAppliedExternalIdentificationAssignment.ReadStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAppliedExternalIdentificationAssignment_ReadStep, None, RWStepAP214_RWAppliedExternalIdentificationAssignment)
RWStepAP214_RWAppliedExternalIdentificationAssignment.WriteStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAppliedExternalIdentificationAssignment_WriteStep, None, RWStepAP214_RWAppliedExternalIdentificationAssignment)
RWStepAP214_RWAppliedExternalIdentificationAssignment.Share = new_instancemethod(_RWStepAP214.RWStepAP214_RWAppliedExternalIdentificationAssignment_Share, None, RWStepAP214_RWAppliedExternalIdentificationAssignment)
RWStepAP214_RWAppliedExternalIdentificationAssignment_swigregister = _RWStepAP214.RWStepAP214_RWAppliedExternalIdentificationAssignment_swigregister
RWStepAP214_RWAppliedExternalIdentificationAssignment_swigregister(RWStepAP214_RWAppliedExternalIdentificationAssignment)

class RWStepAP214_RWAppliedGroupAssignment(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        * Empty constructor

        :rtype: None

        """
        _RWStepAP214.RWStepAP214_RWAppliedGroupAssignment_swiginit(self, _RWStepAP214.new_RWStepAP214_RWAppliedGroupAssignment(*args))

    def ReadStep(self, *args) -> "void":
        """
        * Reads AppliedGroupAssignment

        :param data:
        :type data: Handle_StepData_StepReaderData &
        :param num:
        :type num: int
        :param ach:
        :type ach: Handle_Interface_Check &
        :param ent:
        :type ent: Handle_StepAP214_AppliedGroupAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAppliedGroupAssignment_ReadStep(self, *args)


    def WriteStep(self, *args) -> "void":
        """
        * Writes AppliedGroupAssignment

        :param SW:
        :type SW: StepData_StepWriter &
        :param ent:
        :type ent: Handle_StepAP214_AppliedGroupAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAppliedGroupAssignment_WriteStep(self, *args)


    def Share(self, *args) -> "void":
        """
        * Fills data for graph (shared items)

        :param ent:
        :type ent: Handle_StepAP214_AppliedGroupAssignment &
        :param iter:
        :type iter: Interface_EntityIterator &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAppliedGroupAssignment_Share(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _RWStepAP214.delete_RWStepAP214_RWAppliedGroupAssignment
RWStepAP214_RWAppliedGroupAssignment.ReadStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAppliedGroupAssignment_ReadStep, None, RWStepAP214_RWAppliedGroupAssignment)
RWStepAP214_RWAppliedGroupAssignment.WriteStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAppliedGroupAssignment_WriteStep, None, RWStepAP214_RWAppliedGroupAssignment)
RWStepAP214_RWAppliedGroupAssignment.Share = new_instancemethod(_RWStepAP214.RWStepAP214_RWAppliedGroupAssignment_Share, None, RWStepAP214_RWAppliedGroupAssignment)
RWStepAP214_RWAppliedGroupAssignment_swigregister = _RWStepAP214.RWStepAP214_RWAppliedGroupAssignment_swigregister
RWStepAP214_RWAppliedGroupAssignment_swigregister(RWStepAP214_RWAppliedGroupAssignment)

class RWStepAP214_RWAppliedOrganizationAssignment(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        """
        _RWStepAP214.RWStepAP214_RWAppliedOrganizationAssignment_swiginit(self, _RWStepAP214.new_RWStepAP214_RWAppliedOrganizationAssignment(*args))

    def ReadStep(self, *args) -> "void":
        """
        :param data:
        :type data: Handle_StepData_StepReaderData &
        :param num:
        :type num: int
        :param ach:
        :type ach: Handle_Interface_Check &
        :param ent:
        :type ent: Handle_StepAP214_AppliedOrganizationAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAppliedOrganizationAssignment_ReadStep(self, *args)


    def WriteStep(self, *args) -> "void":
        """
        :param SW:
        :type SW: StepData_StepWriter &
        :param ent:
        :type ent: Handle_StepAP214_AppliedOrganizationAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAppliedOrganizationAssignment_WriteStep(self, *args)


    def Share(self, *args) -> "void":
        """
        :param ent:
        :type ent: Handle_StepAP214_AppliedOrganizationAssignment &
        :param iter:
        :type iter: Interface_EntityIterator &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAppliedOrganizationAssignment_Share(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _RWStepAP214.delete_RWStepAP214_RWAppliedOrganizationAssignment
RWStepAP214_RWAppliedOrganizationAssignment.ReadStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAppliedOrganizationAssignment_ReadStep, None, RWStepAP214_RWAppliedOrganizationAssignment)
RWStepAP214_RWAppliedOrganizationAssignment.WriteStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAppliedOrganizationAssignment_WriteStep, None, RWStepAP214_RWAppliedOrganizationAssignment)
RWStepAP214_RWAppliedOrganizationAssignment.Share = new_instancemethod(_RWStepAP214.RWStepAP214_RWAppliedOrganizationAssignment_Share, None, RWStepAP214_RWAppliedOrganizationAssignment)
RWStepAP214_RWAppliedOrganizationAssignment_swigregister = _RWStepAP214.RWStepAP214_RWAppliedOrganizationAssignment_swigregister
RWStepAP214_RWAppliedOrganizationAssignment_swigregister(RWStepAP214_RWAppliedOrganizationAssignment)

class RWStepAP214_RWAppliedPersonAndOrganizationAssignment(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        """
        _RWStepAP214.RWStepAP214_RWAppliedPersonAndOrganizationAssignment_swiginit(self, _RWStepAP214.new_RWStepAP214_RWAppliedPersonAndOrganizationAssignment(*args))

    def ReadStep(self, *args) -> "void":
        """
        :param data:
        :type data: Handle_StepData_StepReaderData &
        :param num:
        :type num: int
        :param ach:
        :type ach: Handle_Interface_Check &
        :param ent:
        :type ent: Handle_StepAP214_AppliedPersonAndOrganizationAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAppliedPersonAndOrganizationAssignment_ReadStep(self, *args)


    def WriteStep(self, *args) -> "void":
        """
        :param SW:
        :type SW: StepData_StepWriter &
        :param ent:
        :type ent: Handle_StepAP214_AppliedPersonAndOrganizationAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAppliedPersonAndOrganizationAssignment_WriteStep(self, *args)


    def Share(self, *args) -> "void":
        """
        :param ent:
        :type ent: Handle_StepAP214_AppliedPersonAndOrganizationAssignment &
        :param iter:
        :type iter: Interface_EntityIterator &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAppliedPersonAndOrganizationAssignment_Share(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _RWStepAP214.delete_RWStepAP214_RWAppliedPersonAndOrganizationAssignment
RWStepAP214_RWAppliedPersonAndOrganizationAssignment.ReadStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAppliedPersonAndOrganizationAssignment_ReadStep, None, RWStepAP214_RWAppliedPersonAndOrganizationAssignment)
RWStepAP214_RWAppliedPersonAndOrganizationAssignment.WriteStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAppliedPersonAndOrganizationAssignment_WriteStep, None, RWStepAP214_RWAppliedPersonAndOrganizationAssignment)
RWStepAP214_RWAppliedPersonAndOrganizationAssignment.Share = new_instancemethod(_RWStepAP214.RWStepAP214_RWAppliedPersonAndOrganizationAssignment_Share, None, RWStepAP214_RWAppliedPersonAndOrganizationAssignment)
RWStepAP214_RWAppliedPersonAndOrganizationAssignment_swigregister = _RWStepAP214.RWStepAP214_RWAppliedPersonAndOrganizationAssignment_swigregister
RWStepAP214_RWAppliedPersonAndOrganizationAssignment_swigregister(RWStepAP214_RWAppliedPersonAndOrganizationAssignment)

class RWStepAP214_RWAppliedPresentedItem(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        """
        _RWStepAP214.RWStepAP214_RWAppliedPresentedItem_swiginit(self, _RWStepAP214.new_RWStepAP214_RWAppliedPresentedItem(*args))

    def ReadStep(self, *args) -> "void":
        """
        :param data:
        :type data: Handle_StepData_StepReaderData &
        :param num:
        :type num: int
        :param ach:
        :type ach: Handle_Interface_Check &
        :param ent:
        :type ent: Handle_StepAP214_AppliedPresentedItem &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAppliedPresentedItem_ReadStep(self, *args)


    def WriteStep(self, *args) -> "void":
        """
        :param SW:
        :type SW: StepData_StepWriter &
        :param ent:
        :type ent: Handle_StepAP214_AppliedPresentedItem &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAppliedPresentedItem_WriteStep(self, *args)


    def Share(self, *args) -> "void":
        """
        :param ent:
        :type ent: Handle_StepAP214_AppliedPresentedItem &
        :param iter:
        :type iter: Interface_EntityIterator &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAppliedPresentedItem_Share(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _RWStepAP214.delete_RWStepAP214_RWAppliedPresentedItem
RWStepAP214_RWAppliedPresentedItem.ReadStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAppliedPresentedItem_ReadStep, None, RWStepAP214_RWAppliedPresentedItem)
RWStepAP214_RWAppliedPresentedItem.WriteStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAppliedPresentedItem_WriteStep, None, RWStepAP214_RWAppliedPresentedItem)
RWStepAP214_RWAppliedPresentedItem.Share = new_instancemethod(_RWStepAP214.RWStepAP214_RWAppliedPresentedItem_Share, None, RWStepAP214_RWAppliedPresentedItem)
RWStepAP214_RWAppliedPresentedItem_swigregister = _RWStepAP214.RWStepAP214_RWAppliedPresentedItem_swigregister
RWStepAP214_RWAppliedPresentedItem_swigregister(RWStepAP214_RWAppliedPresentedItem)

class RWStepAP214_RWAppliedSecurityClassificationAssignment(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        """
        _RWStepAP214.RWStepAP214_RWAppliedSecurityClassificationAssignment_swiginit(self, _RWStepAP214.new_RWStepAP214_RWAppliedSecurityClassificationAssignment(*args))

    def ReadStep(self, *args) -> "void":
        """
        :param data:
        :type data: Handle_StepData_StepReaderData &
        :param num:
        :type num: int
        :param ach:
        :type ach: Handle_Interface_Check &
        :param ent:
        :type ent: Handle_StepAP214_AppliedSecurityClassificationAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAppliedSecurityClassificationAssignment_ReadStep(self, *args)


    def WriteStep(self, *args) -> "void":
        """
        :param SW:
        :type SW: StepData_StepWriter &
        :param ent:
        :type ent: Handle_StepAP214_AppliedSecurityClassificationAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAppliedSecurityClassificationAssignment_WriteStep(self, *args)


    def Share(self, *args) -> "void":
        """
        :param ent:
        :type ent: Handle_StepAP214_AppliedSecurityClassificationAssignment &
        :param iter:
        :type iter: Interface_EntityIterator &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAppliedSecurityClassificationAssignment_Share(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _RWStepAP214.delete_RWStepAP214_RWAppliedSecurityClassificationAssignment
RWStepAP214_RWAppliedSecurityClassificationAssignment.ReadStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAppliedSecurityClassificationAssignment_ReadStep, None, RWStepAP214_RWAppliedSecurityClassificationAssignment)
RWStepAP214_RWAppliedSecurityClassificationAssignment.WriteStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAppliedSecurityClassificationAssignment_WriteStep, None, RWStepAP214_RWAppliedSecurityClassificationAssignment)
RWStepAP214_RWAppliedSecurityClassificationAssignment.Share = new_instancemethod(_RWStepAP214.RWStepAP214_RWAppliedSecurityClassificationAssignment_Share, None, RWStepAP214_RWAppliedSecurityClassificationAssignment)
RWStepAP214_RWAppliedSecurityClassificationAssignment_swigregister = _RWStepAP214.RWStepAP214_RWAppliedSecurityClassificationAssignment_swigregister
RWStepAP214_RWAppliedSecurityClassificationAssignment_swigregister(RWStepAP214_RWAppliedSecurityClassificationAssignment)

class RWStepAP214_RWAutoDesignActualDateAndTimeAssignment(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        """
        _RWStepAP214.RWStepAP214_RWAutoDesignActualDateAndTimeAssignment_swiginit(self, _RWStepAP214.new_RWStepAP214_RWAutoDesignActualDateAndTimeAssignment(*args))

    def ReadStep(self, *args) -> "void":
        """
        :param data:
        :type data: Handle_StepData_StepReaderData &
        :param num:
        :type num: int
        :param ach:
        :type ach: Handle_Interface_Check &
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignActualDateAndTimeAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignActualDateAndTimeAssignment_ReadStep(self, *args)


    def WriteStep(self, *args) -> "void":
        """
        :param SW:
        :type SW: StepData_StepWriter &
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignActualDateAndTimeAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignActualDateAndTimeAssignment_WriteStep(self, *args)


    def Share(self, *args) -> "void":
        """
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignActualDateAndTimeAssignment &
        :param iter:
        :type iter: Interface_EntityIterator &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignActualDateAndTimeAssignment_Share(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _RWStepAP214.delete_RWStepAP214_RWAutoDesignActualDateAndTimeAssignment
RWStepAP214_RWAutoDesignActualDateAndTimeAssignment.ReadStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignActualDateAndTimeAssignment_ReadStep, None, RWStepAP214_RWAutoDesignActualDateAndTimeAssignment)
RWStepAP214_RWAutoDesignActualDateAndTimeAssignment.WriteStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignActualDateAndTimeAssignment_WriteStep, None, RWStepAP214_RWAutoDesignActualDateAndTimeAssignment)
RWStepAP214_RWAutoDesignActualDateAndTimeAssignment.Share = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignActualDateAndTimeAssignment_Share, None, RWStepAP214_RWAutoDesignActualDateAndTimeAssignment)
RWStepAP214_RWAutoDesignActualDateAndTimeAssignment_swigregister = _RWStepAP214.RWStepAP214_RWAutoDesignActualDateAndTimeAssignment_swigregister
RWStepAP214_RWAutoDesignActualDateAndTimeAssignment_swigregister(RWStepAP214_RWAutoDesignActualDateAndTimeAssignment)

class RWStepAP214_RWAutoDesignActualDateAssignment(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        """
        _RWStepAP214.RWStepAP214_RWAutoDesignActualDateAssignment_swiginit(self, _RWStepAP214.new_RWStepAP214_RWAutoDesignActualDateAssignment(*args))

    def ReadStep(self, *args) -> "void":
        """
        :param data:
        :type data: Handle_StepData_StepReaderData &
        :param num:
        :type num: int
        :param ach:
        :type ach: Handle_Interface_Check &
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignActualDateAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignActualDateAssignment_ReadStep(self, *args)


    def WriteStep(self, *args) -> "void":
        """
        :param SW:
        :type SW: StepData_StepWriter &
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignActualDateAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignActualDateAssignment_WriteStep(self, *args)


    def Share(self, *args) -> "void":
        """
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignActualDateAssignment &
        :param iter:
        :type iter: Interface_EntityIterator &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignActualDateAssignment_Share(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _RWStepAP214.delete_RWStepAP214_RWAutoDesignActualDateAssignment
RWStepAP214_RWAutoDesignActualDateAssignment.ReadStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignActualDateAssignment_ReadStep, None, RWStepAP214_RWAutoDesignActualDateAssignment)
RWStepAP214_RWAutoDesignActualDateAssignment.WriteStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignActualDateAssignment_WriteStep, None, RWStepAP214_RWAutoDesignActualDateAssignment)
RWStepAP214_RWAutoDesignActualDateAssignment.Share = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignActualDateAssignment_Share, None, RWStepAP214_RWAutoDesignActualDateAssignment)
RWStepAP214_RWAutoDesignActualDateAssignment_swigregister = _RWStepAP214.RWStepAP214_RWAutoDesignActualDateAssignment_swigregister
RWStepAP214_RWAutoDesignActualDateAssignment_swigregister(RWStepAP214_RWAutoDesignActualDateAssignment)

class RWStepAP214_RWAutoDesignApprovalAssignment(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        """
        _RWStepAP214.RWStepAP214_RWAutoDesignApprovalAssignment_swiginit(self, _RWStepAP214.new_RWStepAP214_RWAutoDesignApprovalAssignment(*args))

    def ReadStep(self, *args) -> "void":
        """
        :param data:
        :type data: Handle_StepData_StepReaderData &
        :param num:
        :type num: int
        :param ach:
        :type ach: Handle_Interface_Check &
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignApprovalAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignApprovalAssignment_ReadStep(self, *args)


    def WriteStep(self, *args) -> "void":
        """
        :param SW:
        :type SW: StepData_StepWriter &
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignApprovalAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignApprovalAssignment_WriteStep(self, *args)


    def Share(self, *args) -> "void":
        """
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignApprovalAssignment &
        :param iter:
        :type iter: Interface_EntityIterator &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignApprovalAssignment_Share(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _RWStepAP214.delete_RWStepAP214_RWAutoDesignApprovalAssignment
RWStepAP214_RWAutoDesignApprovalAssignment.ReadStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignApprovalAssignment_ReadStep, None, RWStepAP214_RWAutoDesignApprovalAssignment)
RWStepAP214_RWAutoDesignApprovalAssignment.WriteStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignApprovalAssignment_WriteStep, None, RWStepAP214_RWAutoDesignApprovalAssignment)
RWStepAP214_RWAutoDesignApprovalAssignment.Share = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignApprovalAssignment_Share, None, RWStepAP214_RWAutoDesignApprovalAssignment)
RWStepAP214_RWAutoDesignApprovalAssignment_swigregister = _RWStepAP214.RWStepAP214_RWAutoDesignApprovalAssignment_swigregister
RWStepAP214_RWAutoDesignApprovalAssignment_swigregister(RWStepAP214_RWAutoDesignApprovalAssignment)

class RWStepAP214_RWAutoDesignDateAndPersonAssignment(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        """
        _RWStepAP214.RWStepAP214_RWAutoDesignDateAndPersonAssignment_swiginit(self, _RWStepAP214.new_RWStepAP214_RWAutoDesignDateAndPersonAssignment(*args))

    def ReadStep(self, *args) -> "void":
        """
        :param data:
        :type data: Handle_StepData_StepReaderData &
        :param num:
        :type num: int
        :param ach:
        :type ach: Handle_Interface_Check &
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignDateAndPersonAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignDateAndPersonAssignment_ReadStep(self, *args)


    def WriteStep(self, *args) -> "void":
        """
        :param SW:
        :type SW: StepData_StepWriter &
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignDateAndPersonAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignDateAndPersonAssignment_WriteStep(self, *args)


    def Share(self, *args) -> "void":
        """
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignDateAndPersonAssignment &
        :param iter:
        :type iter: Interface_EntityIterator &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignDateAndPersonAssignment_Share(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _RWStepAP214.delete_RWStepAP214_RWAutoDesignDateAndPersonAssignment
RWStepAP214_RWAutoDesignDateAndPersonAssignment.ReadStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignDateAndPersonAssignment_ReadStep, None, RWStepAP214_RWAutoDesignDateAndPersonAssignment)
RWStepAP214_RWAutoDesignDateAndPersonAssignment.WriteStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignDateAndPersonAssignment_WriteStep, None, RWStepAP214_RWAutoDesignDateAndPersonAssignment)
RWStepAP214_RWAutoDesignDateAndPersonAssignment.Share = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignDateAndPersonAssignment_Share, None, RWStepAP214_RWAutoDesignDateAndPersonAssignment)
RWStepAP214_RWAutoDesignDateAndPersonAssignment_swigregister = _RWStepAP214.RWStepAP214_RWAutoDesignDateAndPersonAssignment_swigregister
RWStepAP214_RWAutoDesignDateAndPersonAssignment_swigregister(RWStepAP214_RWAutoDesignDateAndPersonAssignment)

class RWStepAP214_RWAutoDesignDocumentReference(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        """
        _RWStepAP214.RWStepAP214_RWAutoDesignDocumentReference_swiginit(self, _RWStepAP214.new_RWStepAP214_RWAutoDesignDocumentReference(*args))

    def ReadStep(self, *args) -> "void":
        """
        :param data:
        :type data: Handle_StepData_StepReaderData &
        :param num:
        :type num: int
        :param ach:
        :type ach: Handle_Interface_Check &
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignDocumentReference &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignDocumentReference_ReadStep(self, *args)


    def WriteStep(self, *args) -> "void":
        """
        :param SW:
        :type SW: StepData_StepWriter &
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignDocumentReference &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignDocumentReference_WriteStep(self, *args)


    def Share(self, *args) -> "void":
        """
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignDocumentReference &
        :param iter:
        :type iter: Interface_EntityIterator &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignDocumentReference_Share(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _RWStepAP214.delete_RWStepAP214_RWAutoDesignDocumentReference
RWStepAP214_RWAutoDesignDocumentReference.ReadStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignDocumentReference_ReadStep, None, RWStepAP214_RWAutoDesignDocumentReference)
RWStepAP214_RWAutoDesignDocumentReference.WriteStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignDocumentReference_WriteStep, None, RWStepAP214_RWAutoDesignDocumentReference)
RWStepAP214_RWAutoDesignDocumentReference.Share = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignDocumentReference_Share, None, RWStepAP214_RWAutoDesignDocumentReference)
RWStepAP214_RWAutoDesignDocumentReference_swigregister = _RWStepAP214.RWStepAP214_RWAutoDesignDocumentReference_swigregister
RWStepAP214_RWAutoDesignDocumentReference_swigregister(RWStepAP214_RWAutoDesignDocumentReference)

class RWStepAP214_RWAutoDesignGroupAssignment(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        """
        _RWStepAP214.RWStepAP214_RWAutoDesignGroupAssignment_swiginit(self, _RWStepAP214.new_RWStepAP214_RWAutoDesignGroupAssignment(*args))

    def ReadStep(self, *args) -> "void":
        """
        :param data:
        :type data: Handle_StepData_StepReaderData &
        :param num:
        :type num: int
        :param ach:
        :type ach: Handle_Interface_Check &
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignGroupAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignGroupAssignment_ReadStep(self, *args)


    def WriteStep(self, *args) -> "void":
        """
        :param SW:
        :type SW: StepData_StepWriter &
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignGroupAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignGroupAssignment_WriteStep(self, *args)


    def Share(self, *args) -> "void":
        """
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignGroupAssignment &
        :param iter:
        :type iter: Interface_EntityIterator &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignGroupAssignment_Share(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _RWStepAP214.delete_RWStepAP214_RWAutoDesignGroupAssignment
RWStepAP214_RWAutoDesignGroupAssignment.ReadStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignGroupAssignment_ReadStep, None, RWStepAP214_RWAutoDesignGroupAssignment)
RWStepAP214_RWAutoDesignGroupAssignment.WriteStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignGroupAssignment_WriteStep, None, RWStepAP214_RWAutoDesignGroupAssignment)
RWStepAP214_RWAutoDesignGroupAssignment.Share = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignGroupAssignment_Share, None, RWStepAP214_RWAutoDesignGroupAssignment)
RWStepAP214_RWAutoDesignGroupAssignment_swigregister = _RWStepAP214.RWStepAP214_RWAutoDesignGroupAssignment_swigregister
RWStepAP214_RWAutoDesignGroupAssignment_swigregister(RWStepAP214_RWAutoDesignGroupAssignment)

class RWStepAP214_RWAutoDesignNominalDateAndTimeAssignment(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        """
        _RWStepAP214.RWStepAP214_RWAutoDesignNominalDateAndTimeAssignment_swiginit(self, _RWStepAP214.new_RWStepAP214_RWAutoDesignNominalDateAndTimeAssignment(*args))

    def ReadStep(self, *args) -> "void":
        """
        :param data:
        :type data: Handle_StepData_StepReaderData &
        :param num:
        :type num: int
        :param ach:
        :type ach: Handle_Interface_Check &
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignNominalDateAndTimeAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignNominalDateAndTimeAssignment_ReadStep(self, *args)


    def WriteStep(self, *args) -> "void":
        """
        :param SW:
        :type SW: StepData_StepWriter &
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignNominalDateAndTimeAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignNominalDateAndTimeAssignment_WriteStep(self, *args)


    def Share(self, *args) -> "void":
        """
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignNominalDateAndTimeAssignment &
        :param iter:
        :type iter: Interface_EntityIterator &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignNominalDateAndTimeAssignment_Share(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _RWStepAP214.delete_RWStepAP214_RWAutoDesignNominalDateAndTimeAssignment
RWStepAP214_RWAutoDesignNominalDateAndTimeAssignment.ReadStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignNominalDateAndTimeAssignment_ReadStep, None, RWStepAP214_RWAutoDesignNominalDateAndTimeAssignment)
RWStepAP214_RWAutoDesignNominalDateAndTimeAssignment.WriteStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignNominalDateAndTimeAssignment_WriteStep, None, RWStepAP214_RWAutoDesignNominalDateAndTimeAssignment)
RWStepAP214_RWAutoDesignNominalDateAndTimeAssignment.Share = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignNominalDateAndTimeAssignment_Share, None, RWStepAP214_RWAutoDesignNominalDateAndTimeAssignment)
RWStepAP214_RWAutoDesignNominalDateAndTimeAssignment_swigregister = _RWStepAP214.RWStepAP214_RWAutoDesignNominalDateAndTimeAssignment_swigregister
RWStepAP214_RWAutoDesignNominalDateAndTimeAssignment_swigregister(RWStepAP214_RWAutoDesignNominalDateAndTimeAssignment)

class RWStepAP214_RWAutoDesignNominalDateAssignment(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        """
        _RWStepAP214.RWStepAP214_RWAutoDesignNominalDateAssignment_swiginit(self, _RWStepAP214.new_RWStepAP214_RWAutoDesignNominalDateAssignment(*args))

    def ReadStep(self, *args) -> "void":
        """
        :param data:
        :type data: Handle_StepData_StepReaderData &
        :param num:
        :type num: int
        :param ach:
        :type ach: Handle_Interface_Check &
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignNominalDateAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignNominalDateAssignment_ReadStep(self, *args)


    def WriteStep(self, *args) -> "void":
        """
        :param SW:
        :type SW: StepData_StepWriter &
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignNominalDateAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignNominalDateAssignment_WriteStep(self, *args)


    def Share(self, *args) -> "void":
        """
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignNominalDateAssignment &
        :param iter:
        :type iter: Interface_EntityIterator &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignNominalDateAssignment_Share(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _RWStepAP214.delete_RWStepAP214_RWAutoDesignNominalDateAssignment
RWStepAP214_RWAutoDesignNominalDateAssignment.ReadStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignNominalDateAssignment_ReadStep, None, RWStepAP214_RWAutoDesignNominalDateAssignment)
RWStepAP214_RWAutoDesignNominalDateAssignment.WriteStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignNominalDateAssignment_WriteStep, None, RWStepAP214_RWAutoDesignNominalDateAssignment)
RWStepAP214_RWAutoDesignNominalDateAssignment.Share = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignNominalDateAssignment_Share, None, RWStepAP214_RWAutoDesignNominalDateAssignment)
RWStepAP214_RWAutoDesignNominalDateAssignment_swigregister = _RWStepAP214.RWStepAP214_RWAutoDesignNominalDateAssignment_swigregister
RWStepAP214_RWAutoDesignNominalDateAssignment_swigregister(RWStepAP214_RWAutoDesignNominalDateAssignment)

class RWStepAP214_RWAutoDesignOrganizationAssignment(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        """
        _RWStepAP214.RWStepAP214_RWAutoDesignOrganizationAssignment_swiginit(self, _RWStepAP214.new_RWStepAP214_RWAutoDesignOrganizationAssignment(*args))

    def ReadStep(self, *args) -> "void":
        """
        :param data:
        :type data: Handle_StepData_StepReaderData &
        :param num:
        :type num: int
        :param ach:
        :type ach: Handle_Interface_Check &
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignOrganizationAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignOrganizationAssignment_ReadStep(self, *args)


    def WriteStep(self, *args) -> "void":
        """
        :param SW:
        :type SW: StepData_StepWriter &
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignOrganizationAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignOrganizationAssignment_WriteStep(self, *args)


    def Share(self, *args) -> "void":
        """
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignOrganizationAssignment &
        :param iter:
        :type iter: Interface_EntityIterator &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignOrganizationAssignment_Share(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _RWStepAP214.delete_RWStepAP214_RWAutoDesignOrganizationAssignment
RWStepAP214_RWAutoDesignOrganizationAssignment.ReadStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignOrganizationAssignment_ReadStep, None, RWStepAP214_RWAutoDesignOrganizationAssignment)
RWStepAP214_RWAutoDesignOrganizationAssignment.WriteStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignOrganizationAssignment_WriteStep, None, RWStepAP214_RWAutoDesignOrganizationAssignment)
RWStepAP214_RWAutoDesignOrganizationAssignment.Share = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignOrganizationAssignment_Share, None, RWStepAP214_RWAutoDesignOrganizationAssignment)
RWStepAP214_RWAutoDesignOrganizationAssignment_swigregister = _RWStepAP214.RWStepAP214_RWAutoDesignOrganizationAssignment_swigregister
RWStepAP214_RWAutoDesignOrganizationAssignment_swigregister(RWStepAP214_RWAutoDesignOrganizationAssignment)

class RWStepAP214_RWAutoDesignPersonAndOrganizationAssignment(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        """
        _RWStepAP214.RWStepAP214_RWAutoDesignPersonAndOrganizationAssignment_swiginit(self, _RWStepAP214.new_RWStepAP214_RWAutoDesignPersonAndOrganizationAssignment(*args))

    def ReadStep(self, *args) -> "void":
        """
        :param data:
        :type data: Handle_StepData_StepReaderData &
        :param num:
        :type num: int
        :param ach:
        :type ach: Handle_Interface_Check &
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignPersonAndOrganizationAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignPersonAndOrganizationAssignment_ReadStep(self, *args)


    def WriteStep(self, *args) -> "void":
        """
        :param SW:
        :type SW: StepData_StepWriter &
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignPersonAndOrganizationAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignPersonAndOrganizationAssignment_WriteStep(self, *args)


    def Share(self, *args) -> "void":
        """
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignPersonAndOrganizationAssignment &
        :param iter:
        :type iter: Interface_EntityIterator &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignPersonAndOrganizationAssignment_Share(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _RWStepAP214.delete_RWStepAP214_RWAutoDesignPersonAndOrganizationAssignment
RWStepAP214_RWAutoDesignPersonAndOrganizationAssignment.ReadStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignPersonAndOrganizationAssignment_ReadStep, None, RWStepAP214_RWAutoDesignPersonAndOrganizationAssignment)
RWStepAP214_RWAutoDesignPersonAndOrganizationAssignment.WriteStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignPersonAndOrganizationAssignment_WriteStep, None, RWStepAP214_RWAutoDesignPersonAndOrganizationAssignment)
RWStepAP214_RWAutoDesignPersonAndOrganizationAssignment.Share = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignPersonAndOrganizationAssignment_Share, None, RWStepAP214_RWAutoDesignPersonAndOrganizationAssignment)
RWStepAP214_RWAutoDesignPersonAndOrganizationAssignment_swigregister = _RWStepAP214.RWStepAP214_RWAutoDesignPersonAndOrganizationAssignment_swigregister
RWStepAP214_RWAutoDesignPersonAndOrganizationAssignment_swigregister(RWStepAP214_RWAutoDesignPersonAndOrganizationAssignment)

class RWStepAP214_RWAutoDesignPresentedItem(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        """
        _RWStepAP214.RWStepAP214_RWAutoDesignPresentedItem_swiginit(self, _RWStepAP214.new_RWStepAP214_RWAutoDesignPresentedItem(*args))

    def ReadStep(self, *args) -> "void":
        """
        :param data:
        :type data: Handle_StepData_StepReaderData &
        :param num:
        :type num: int
        :param ach:
        :type ach: Handle_Interface_Check &
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignPresentedItem &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignPresentedItem_ReadStep(self, *args)


    def WriteStep(self, *args) -> "void":
        """
        :param SW:
        :type SW: StepData_StepWriter &
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignPresentedItem &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignPresentedItem_WriteStep(self, *args)


    def Share(self, *args) -> "void":
        """
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignPresentedItem &
        :param iter:
        :type iter: Interface_EntityIterator &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignPresentedItem_Share(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _RWStepAP214.delete_RWStepAP214_RWAutoDesignPresentedItem
RWStepAP214_RWAutoDesignPresentedItem.ReadStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignPresentedItem_ReadStep, None, RWStepAP214_RWAutoDesignPresentedItem)
RWStepAP214_RWAutoDesignPresentedItem.WriteStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignPresentedItem_WriteStep, None, RWStepAP214_RWAutoDesignPresentedItem)
RWStepAP214_RWAutoDesignPresentedItem.Share = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignPresentedItem_Share, None, RWStepAP214_RWAutoDesignPresentedItem)
RWStepAP214_RWAutoDesignPresentedItem_swigregister = _RWStepAP214.RWStepAP214_RWAutoDesignPresentedItem_swigregister
RWStepAP214_RWAutoDesignPresentedItem_swigregister(RWStepAP214_RWAutoDesignPresentedItem)

class RWStepAP214_RWAutoDesignSecurityClassificationAssignment(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        """
        _RWStepAP214.RWStepAP214_RWAutoDesignSecurityClassificationAssignment_swiginit(self, _RWStepAP214.new_RWStepAP214_RWAutoDesignSecurityClassificationAssignment(*args))

    def ReadStep(self, *args) -> "void":
        """
        :param data:
        :type data: Handle_StepData_StepReaderData &
        :param num:
        :type num: int
        :param ach:
        :type ach: Handle_Interface_Check &
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignSecurityClassificationAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignSecurityClassificationAssignment_ReadStep(self, *args)


    def WriteStep(self, *args) -> "void":
        """
        :param SW:
        :type SW: StepData_StepWriter &
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignSecurityClassificationAssignment &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignSecurityClassificationAssignment_WriteStep(self, *args)


    def Share(self, *args) -> "void":
        """
        :param ent:
        :type ent: Handle_StepAP214_AutoDesignSecurityClassificationAssignment &
        :param iter:
        :type iter: Interface_EntityIterator &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWAutoDesignSecurityClassificationAssignment_Share(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _RWStepAP214.delete_RWStepAP214_RWAutoDesignSecurityClassificationAssignment
RWStepAP214_RWAutoDesignSecurityClassificationAssignment.ReadStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignSecurityClassificationAssignment_ReadStep, None, RWStepAP214_RWAutoDesignSecurityClassificationAssignment)
RWStepAP214_RWAutoDesignSecurityClassificationAssignment.WriteStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignSecurityClassificationAssignment_WriteStep, None, RWStepAP214_RWAutoDesignSecurityClassificationAssignment)
RWStepAP214_RWAutoDesignSecurityClassificationAssignment.Share = new_instancemethod(_RWStepAP214.RWStepAP214_RWAutoDesignSecurityClassificationAssignment_Share, None, RWStepAP214_RWAutoDesignSecurityClassificationAssignment)
RWStepAP214_RWAutoDesignSecurityClassificationAssignment_swigregister = _RWStepAP214.RWStepAP214_RWAutoDesignSecurityClassificationAssignment_swigregister
RWStepAP214_RWAutoDesignSecurityClassificationAssignment_swigregister(RWStepAP214_RWAutoDesignSecurityClassificationAssignment)

class RWStepAP214_RWClass(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        * Empty constructor

        :rtype: None

        """
        _RWStepAP214.RWStepAP214_RWClass_swiginit(self, _RWStepAP214.new_RWStepAP214_RWClass(*args))

    def ReadStep(self, *args) -> "void":
        """
        * Reads Class

        :param data:
        :type data: Handle_StepData_StepReaderData &
        :param num:
        :type num: int
        :param ach:
        :type ach: Handle_Interface_Check &
        :param ent:
        :type ent: Handle_StepAP214_Class &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWClass_ReadStep(self, *args)


    def WriteStep(self, *args) -> "void":
        """
        * Writes Class

        :param SW:
        :type SW: StepData_StepWriter &
        :param ent:
        :type ent: Handle_StepAP214_Class &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWClass_WriteStep(self, *args)


    def Share(self, *args) -> "void":
        """
        * Fills data for graph (shared items)

        :param ent:
        :type ent: Handle_StepAP214_Class &
        :param iter:
        :type iter: Interface_EntityIterator &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWClass_Share(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _RWStepAP214.delete_RWStepAP214_RWClass
RWStepAP214_RWClass.ReadStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWClass_ReadStep, None, RWStepAP214_RWClass)
RWStepAP214_RWClass.WriteStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWClass_WriteStep, None, RWStepAP214_RWClass)
RWStepAP214_RWClass.Share = new_instancemethod(_RWStepAP214.RWStepAP214_RWClass_Share, None, RWStepAP214_RWClass)
RWStepAP214_RWClass_swigregister = _RWStepAP214.RWStepAP214_RWClass_swigregister
RWStepAP214_RWClass_swigregister(RWStepAP214_RWClass)

class RWStepAP214_RWExternallyDefinedClass(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        * Empty constructor

        :rtype: None

        """
        _RWStepAP214.RWStepAP214_RWExternallyDefinedClass_swiginit(self, _RWStepAP214.new_RWStepAP214_RWExternallyDefinedClass(*args))

    def ReadStep(self, *args) -> "void":
        """
        * Reads ExternallyDefinedClass

        :param data:
        :type data: Handle_StepData_StepReaderData &
        :param num:
        :type num: int
        :param ach:
        :type ach: Handle_Interface_Check &
        :param ent:
        :type ent: Handle_StepAP214_ExternallyDefinedClass &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWExternallyDefinedClass_ReadStep(self, *args)


    def WriteStep(self, *args) -> "void":
        """
        * Writes ExternallyDefinedClass

        :param SW:
        :type SW: StepData_StepWriter &
        :param ent:
        :type ent: Handle_StepAP214_ExternallyDefinedClass &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWExternallyDefinedClass_WriteStep(self, *args)


    def Share(self, *args) -> "void":
        """
        * Fills data for graph (shared items)

        :param ent:
        :type ent: Handle_StepAP214_ExternallyDefinedClass &
        :param iter:
        :type iter: Interface_EntityIterator &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWExternallyDefinedClass_Share(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _RWStepAP214.delete_RWStepAP214_RWExternallyDefinedClass
RWStepAP214_RWExternallyDefinedClass.ReadStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWExternallyDefinedClass_ReadStep, None, RWStepAP214_RWExternallyDefinedClass)
RWStepAP214_RWExternallyDefinedClass.WriteStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWExternallyDefinedClass_WriteStep, None, RWStepAP214_RWExternallyDefinedClass)
RWStepAP214_RWExternallyDefinedClass.Share = new_instancemethod(_RWStepAP214.RWStepAP214_RWExternallyDefinedClass_Share, None, RWStepAP214_RWExternallyDefinedClass)
RWStepAP214_RWExternallyDefinedClass_swigregister = _RWStepAP214.RWStepAP214_RWExternallyDefinedClass_swigregister
RWStepAP214_RWExternallyDefinedClass_swigregister(RWStepAP214_RWExternallyDefinedClass)

class RWStepAP214_RWExternallyDefinedGeneralProperty(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        * Empty constructor

        :rtype: None

        """
        _RWStepAP214.RWStepAP214_RWExternallyDefinedGeneralProperty_swiginit(self, _RWStepAP214.new_RWStepAP214_RWExternallyDefinedGeneralProperty(*args))

    def ReadStep(self, *args) -> "void":
        """
        * Reads ExternallyDefinedGeneralProperty

        :param data:
        :type data: Handle_StepData_StepReaderData &
        :param num:
        :type num: int
        :param ach:
        :type ach: Handle_Interface_Check &
        :param ent:
        :type ent: Handle_StepAP214_ExternallyDefinedGeneralProperty &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWExternallyDefinedGeneralProperty_ReadStep(self, *args)


    def WriteStep(self, *args) -> "void":
        """
        * Writes ExternallyDefinedGeneralProperty

        :param SW:
        :type SW: StepData_StepWriter &
        :param ent:
        :type ent: Handle_StepAP214_ExternallyDefinedGeneralProperty &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWExternallyDefinedGeneralProperty_WriteStep(self, *args)


    def Share(self, *args) -> "void":
        """
        * Fills data for graph (shared items)

        :param ent:
        :type ent: Handle_StepAP214_ExternallyDefinedGeneralProperty &
        :param iter:
        :type iter: Interface_EntityIterator &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWExternallyDefinedGeneralProperty_Share(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _RWStepAP214.delete_RWStepAP214_RWExternallyDefinedGeneralProperty
RWStepAP214_RWExternallyDefinedGeneralProperty.ReadStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWExternallyDefinedGeneralProperty_ReadStep, None, RWStepAP214_RWExternallyDefinedGeneralProperty)
RWStepAP214_RWExternallyDefinedGeneralProperty.WriteStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWExternallyDefinedGeneralProperty_WriteStep, None, RWStepAP214_RWExternallyDefinedGeneralProperty)
RWStepAP214_RWExternallyDefinedGeneralProperty.Share = new_instancemethod(_RWStepAP214.RWStepAP214_RWExternallyDefinedGeneralProperty_Share, None, RWStepAP214_RWExternallyDefinedGeneralProperty)
RWStepAP214_RWExternallyDefinedGeneralProperty_swigregister = _RWStepAP214.RWStepAP214_RWExternallyDefinedGeneralProperty_swigregister
RWStepAP214_RWExternallyDefinedGeneralProperty_swigregister(RWStepAP214_RWExternallyDefinedGeneralProperty)

class RWStepAP214_RWRepItemGroup(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        * Empty constructor

        :rtype: None

        """
        _RWStepAP214.RWStepAP214_RWRepItemGroup_swiginit(self, _RWStepAP214.new_RWStepAP214_RWRepItemGroup(*args))

    def ReadStep(self, *args) -> "void":
        """
        * Reads RepItemGroup

        :param data:
        :type data: Handle_StepData_StepReaderData &
        :param num:
        :type num: int
        :param ach:
        :type ach: Handle_Interface_Check &
        :param ent:
        :type ent: Handle_StepAP214_RepItemGroup &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWRepItemGroup_ReadStep(self, *args)


    def WriteStep(self, *args) -> "void":
        """
        * Writes RepItemGroup

        :param SW:
        :type SW: StepData_StepWriter &
        :param ent:
        :type ent: Handle_StepAP214_RepItemGroup &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWRepItemGroup_WriteStep(self, *args)


    def Share(self, *args) -> "void":
        """
        * Fills data for graph (shared items)

        :param ent:
        :type ent: Handle_StepAP214_RepItemGroup &
        :param iter:
        :type iter: Interface_EntityIterator &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_RWRepItemGroup_Share(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _RWStepAP214.delete_RWStepAP214_RWRepItemGroup
RWStepAP214_RWRepItemGroup.ReadStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWRepItemGroup_ReadStep, None, RWStepAP214_RWRepItemGroup)
RWStepAP214_RWRepItemGroup.WriteStep = new_instancemethod(_RWStepAP214.RWStepAP214_RWRepItemGroup_WriteStep, None, RWStepAP214_RWRepItemGroup)
RWStepAP214_RWRepItemGroup.Share = new_instancemethod(_RWStepAP214.RWStepAP214_RWRepItemGroup_Share, None, RWStepAP214_RWRepItemGroup)
RWStepAP214_RWRepItemGroup_swigregister = _RWStepAP214.RWStepAP214_RWRepItemGroup_swigregister
RWStepAP214_RWRepItemGroup_swigregister(RWStepAP214_RWRepItemGroup)

class RWStepAP214_ReadWriteModule(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        :rtype: None

        """
        _RWStepAP214.RWStepAP214_ReadWriteModule_swiginit(self, _RWStepAP214.new_RWStepAP214_ReadWriteModule(*args))

    def CaseStep(self, *args) -> "Standard_Integer":
        """
        * associates a positive Case Number to each type of StepAP214 entity, given as a String defined in the EXPRESS form

        :param atype:
        :type atype: TCollection_AsciiString &
        :rtype: int

        * associates a positive Case Number to each type of StepAP214 Complex entity, given as a String defined in the EXPRESS form

        :param types:
        :type types: TColStd_SequenceOfAsciiString &
        :rtype: int

        """
        return _RWStepAP214.RWStepAP214_ReadWriteModule_CaseStep(self, *args)


    def IsComplex(self, *args) -> "Standard_Boolean":
        """
        * returns True if the Case Number corresponds to a Complex Type

        :param CN:
        :type CN: int
        :rtype: bool

        """
        return _RWStepAP214.RWStepAP214_ReadWriteModule_IsComplex(self, *args)


    def StepType(self, *args) -> "TCollection_AsciiString const &":
        """
        * returns a StepType (defined in EXPRESS form which belongs to a Type of Entity, identified by its CaseNumber determined by Protocol

        :param CN:
        :type CN: int
        :rtype: TCollection_AsciiString

        """
        return _RWStepAP214.RWStepAP214_ReadWriteModule_StepType(self, *args)


    def ComplexType(self, *args) -> "Standard_Boolean":
        """
        :param CN:
        :type CN: int
        :param types:
        :type types: TColStd_SequenceOfAsciiString &
        :rtype: bool

        """
        return _RWStepAP214.RWStepAP214_ReadWriteModule_ComplexType(self, *args)


    def ReadStep(self, *args) -> "void":
        """
        :param CN:
        :type CN: int
        :param data:
        :type data: Handle_StepData_StepReaderData &
        :param num:
        :type num: int
        :param ach:
        :type ach: Handle_Interface_Check &
        :param ent:
        :type ent: Handle_Standard_Transient &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_ReadWriteModule_ReadStep(self, *args)


    def WriteStep(self, *args) -> "void":
        """
        :param CN:
        :type CN: int
        :param SW:
        :type SW: StepData_StepWriter &
        :param ent:
        :type ent: Handle_Standard_Transient &
        :rtype: None

        """
        return _RWStepAP214.RWStepAP214_ReadWriteModule_WriteStep(self, *args)


    def GetHandle(self):
        try:
            return self.thisHandle
        except:
            self.thisHandle = Handle_RWStepAP214_ReadWriteModule(self)
            self.thisown = False
            return self.thisHandle


    __repr__ = _dumps_object

    __swig_destroy__ = _RWStepAP214.delete_RWStepAP214_ReadWriteModule
RWStepAP214_ReadWriteModule.CaseStep = new_instancemethod(_RWStepAP214.RWStepAP214_ReadWriteModule_CaseStep, None, RWStepAP214_ReadWriteModule)
RWStepAP214_ReadWriteModule.IsComplex = new_instancemethod(_RWStepAP214.RWStepAP214_ReadWriteModule_IsComplex, None, RWStepAP214_ReadWriteModule)
RWStepAP214_ReadWriteModule.StepType = new_instancemethod(_RWStepAP214.RWStepAP214_ReadWriteModule_StepType, None, RWStepAP214_ReadWriteModule)
RWStepAP214_ReadWriteModule.ComplexType = new_instancemethod(_RWStepAP214.RWStepAP214_ReadWriteModule_ComplexType, None, RWStepAP214_ReadWriteModule)
RWStepAP214_ReadWriteModule.ReadStep = new_instancemethod(_RWStepAP214.RWStepAP214_ReadWriteModule_ReadStep, None, RWStepAP214_ReadWriteModule)
RWStepAP214_ReadWriteModule.WriteStep = new_instancemethod(_RWStepAP214.RWStepAP214_ReadWriteModule_WriteStep, None, RWStepAP214_ReadWriteModule)
RWStepAP214_ReadWriteModule_swigregister = _RWStepAP214.RWStepAP214_ReadWriteModule_swigregister
RWStepAP214_ReadWriteModule_swigregister(RWStepAP214_ReadWriteModule)

class Handle_RWStepAP214_ReadWriteModule(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        _RWStepAP214.Handle_RWStepAP214_ReadWriteModule_swiginit(self, _RWStepAP214.new_Handle_RWStepAP214_ReadWriteModule(*args))

            # register the handle in the base object
        if len(args) > 0:
            register_handle(self, args[0])



    DownCast = staticmethod(_RWStepAP214.Handle_RWStepAP214_ReadWriteModule_DownCast)

    def GetObject(self):
        obj = self._get_reference()
        register_handle(self, obj)
        return obj

    __swig_destroy__ = _RWStepAP214.delete_Handle_RWStepAP214_ReadWriteModule
Handle_RWStepAP214_ReadWriteModule.Nullify = new_instancemethod(_RWStepAP214.Handle_RWStepAP214_ReadWriteModule_Nullify, None, Handle_RWStepAP214_ReadWriteModule)
Handle_RWStepAP214_ReadWriteModule.IsNull = new_instancemethod(_RWStepAP214.Handle_RWStepAP214_ReadWriteModule_IsNull, None, Handle_RWStepAP214_ReadWriteModule)
Handle_RWStepAP214_ReadWriteModule._get_reference = new_instancemethod(_RWStepAP214.Handle_RWStepAP214_ReadWriteModule__get_reference, None, Handle_RWStepAP214_ReadWriteModule)
Handle_RWStepAP214_ReadWriteModule_swigregister = _RWStepAP214.Handle_RWStepAP214_ReadWriteModule_swigregister
Handle_RWStepAP214_ReadWriteModule_swigregister(Handle_RWStepAP214_ReadWriteModule)

def Handle_RWStepAP214_ReadWriteModule_DownCast(AnObject: 'Handle_Standard_Transient') -> "Handle_RWStepAP214_ReadWriteModule const":
    return _RWStepAP214.Handle_RWStepAP214_ReadWriteModule_DownCast(AnObject)
Handle_RWStepAP214_ReadWriteModule_DownCast = _RWStepAP214.Handle_RWStepAP214_ReadWriteModule_DownCast



